\input texinfo                              @c -*- texinfo -*-
@afourpaper

@c @include{version.texi}
@set VERSION 0.92

@copying
Copyright @copyright{} 2003, 2004, 2005 Daniel Heck

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end copying

@setfilename enigma.info
@settitle Enigma Manual
@titlepage
@image{images/logo}
@center @titlefont{Enigma Manual}
@center pour version @value{VERSION}
@sp 2
@center Copyright @copyright{} 2003, 2004, 2005 Daniel Heck (@email{dheck@@gmx.de})
@c @title Enigma Manuel
@c @subtitle pour version 0.80
@c @author Daniel Heck (@email{dheck@@gmx.de})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Haut, Introduction, (dir), (dir)
@Haut Enigma

Ce manuel d@'ecrit comment installer Enigma et y jouer.  Il correspond
@`a Enigma version @value{VERSION}.

Copyright @copyright{} 2003, 2004, 2005 Daniel Heck

Copier et distribuer ce fichier, avec ou sans modification,
sont permis par tout moyen sans droit d'auteur @`a condition 
que la notice sur le droit d'auteur et cette notice soient pr@'eserv@'ees.
@c @insertcopying
@end ifnottex

@menu
* Introduction::                Comment commencer avec Enigma
* Le jeu::                      Comment jouer @`a Enigma
* Objets du jeu::               Description de certains objets du jeu
* Triche::                      Astuces pour certains niveaux difficiles
* Cr@'edits::                     Cr@'edits et `Thank You's

@detailmenu
 --- The Detailed Node Listing ---

Introduction

* A propos::                    Certains faits sur Enigma
* Installation::                Obtenir et installer Enigma
* Distribuer Enigma::           Partagez-le avec vos amis!

Le jeu

* Comment commencer::           Naviguer dans les menus et d@'emarrer une partie
* R@`egles du jeu::               Comment jouer @`a Enigma
* Contr@^oles::                   Raccourcis clavier et souris

Comment commencer

* Le menu des niveaux::         Choisir un niveau
* Options de jeu::              Adapter Enigma @`a vos pr@'ef@'erences

R@`egles du jeu

* Paysages normaux::           
* Paysages @`a deux joueurs::       
* Paysages de m@'editation::       

Objets du jeu

* Outils::                       
* Pierres::                      

Outils

* Explosifs::                   Dynamite et bombes
* Parapluies::                   
* Drapeaux::                    Le point de retour

Pierres  

* Pierres mortelles::               
* Pierres d'@'echange::                 
* Miroirs::                     
* Pierres magiques::                
* Pierres Shogun::               
* Pierres @'electriques::             
* Pierres de puzzle::               
* Pierres postales::                 

Triche

* Tutoriel::                    Promenade dans 'advanced tutorial'
* Indices::                     Indices pour plusieurs niveaux

Cr@'edits

* D@'eveloppeurs principaux::             
* Special Thanks::              
* Contributeurs::                
* Logiciels utilis@'es::           

@end detailmenu
@end menu

@node Introduction, Le jeu, Haut, Haut
@chapter Introduction

@menu
* A propos::                    Certains faits sur Enigma
* Installation::                Obtenir et installer Enigma
* Distribuer Enigma::           Partagez-le avec vos amis!
@end menu


@node A propos, Installation, Introduction, Introduction
@section A propos Enigma

Dans les ann@'ees 1990 (peu apr@`es l'@'epoque de N@'eanderthal), l'un des jeux sur ordinateur les plus
intrigants qui soient s'appelait « Oxyd »; il a @'et@'e diffus@'e sur Atari ST puis sur de nombreuses autres
plates-formes par une firme r@'epondant au doux nom de « Dongleware ». Malgr@'e de nombreuses
recherches arch@'eologiques men@'ees conjointement par Lara Croft, Sydney Fox et Indiana Jones, on
n'a jamais prouv@'e l'existence d'un « Oxyd 2 »; n@'eanmoins il y a eu successivement Per.Oxyd, Oxyd
Magnum puis Oxyd Extra. En 2002 Dongleware a abandonn@'e ses activit@'es dans le secteur du jeu et
le jeu Oxyd.
Enigma est un clone d'Oxyd (quelques diff@'erences mais globalement c'est le m@^eme principe). M@^eme
si vous n'avez jamais eu la chance de jouer @`a Oxyd, vous adorerez Enigma si vous aimez r@'efl@'echir et
si vous @^etes habile avec le mulot.
Enigma se t@'el@'echarge sur @uref{www.nongnu.org/enigma} et c'est sur ce site qu'on trouve les nouveaut@'es le
concernant. Ce jeu est libre, ce qui signifie que non seulement vous avez le droit de le copier et de
le distribuer, mais vous y @^etes m@^eme encourag@'e ! (voir la section 1.4 pour plus de d@'etails)


@node Installation, Distribuer Enigma, A propos, Introduction
@section Installation

La derni@`ere version du jeu se t@'el@'echarge sur @uref{www.nongnu.org/enigma/downloads} et le protocole
d'installation diff@`ere selon la plate-forme:

@table @strong
@item Windows
Le jeu est fourni sous la forme d'un ex@'ecutable, qu'il suffit ... d'@'ex@'ecuter !

@item Unix
Il existe des ex@'ecutables binaires pour SuSe, Debian et RedHat; pour les autres, l'usage est de
le compiler @`a partir du source. (des d@'ependances sont n@'ecessaires, elles sont list@'ees sur le site)

@item Mac OS X
L'installation n'est pas n@'ecessaire, il suffit d'ex@'ecuter le fichier 
@file{.dmg} ou le fichier @file{.tar.gz}.

@end table

En cas de probl@`emes d'installations, des conseils sont disponibles sur 
enigma-devel@nongnu.org (dans la langue de Shakespeare toutefois).
Si Enigma ne fonctionne pas sur votre ordinateur, n'h@'esitez pas @`a 
demander de l'aide sur la liste (@email{enigma-devel@@nongnu.org}).

@c @node Emulating Oxyd, Distribuer Enigma, Installation, Introduction
@c @section Emulating Oxyd

@c Comme mentionn@'e dans l'introduction, Enigma descend d'Oxyd; pour autant la compatibilit@'e n'est
@c pas assur@'ee @`a 100%. Notamment il manque plusieurs objets d'Oxyd, et le jeu en r@'eseau n'est pour
@c l'instant pas du tout impl@'ement@'e. Ce qui marche:
@c Les effets sonores d'Oxyd sont importables;
@c La plupart des paysages d'Oxyd sont importables dans Enigma, de la mani@`ere suivante: Enigma
@c cherche automatiquement @`a importer les paysages qu'il cherche par d@'efaut dans les dossiers
@c suivants:

@c @table @strong
@c @item Windows
@c le dossier « data » cr@'e@'e @`a l'installation d'Enigma; typiquement c'est C:\Program
@c Files\Enigma\data

@c @item Unix / OS X
@c Il y a deux emplacements possibles, l'un au niveau du syst@`eme (typiquement
@c « /usr/local/share/enigma »), l'autre au niveau de l'utilisateur courant (un fichier appel@'e « ".enigma »
@c dans le r@'epertoire « home »).

@c Tout ce qu'il reste @`a faire est de copier les fichiers suivants dans le r@'epertoire « data » (en n'oubliant
@c pas que sous Unix la casse doit @^etre respect@'ee):

@c @multitable {Oxyd magnum gold} {@file{oxyd1ibm.dat}}
@c @item @strong{Game}	@tab @strong{Data file}
@c @item Per.Oxyd		@tab @file{peroxyd.dat}
@c @item Oxyd 1		@tab @file{oxyd1ibm.dat}
@c @item Oxyd extra	@tab @file{oxydex.dat}
@c @item Oxyd magnum	@tab @file{oxydmibm.dat}
@c @item Oxyd magnum gold	@tab @file{oxydmgg.dat}
@c @end multitable

@c Per.Oxyd et Oxyd 1 sont « dongleware » (un r@'egime proche du shareware) et peuvent @^etre
@c t@'el@'echarg@'es sur le net (essayez de soumettre @`a votre moteur de recherche favori, les mots « oxyd » et
@c « abandonware »). Par contre les autres fichiers sont toujours commerciaux et il n'est autoris@'e de les
@c utiliser que si on poss@`ede une copie acquise l@'egalement. Pour des questions de droit d'auteur, il n'est
@c pas question d'inclure aucun des fichiers mentionn@'es ci-dessus, dans Enigma; inutile de le demander
@c donc...

@node Distribuer Enigma,  , Installation, Introduction
@section Distribuer Enigma

Enigma est couvert par la licence GPL (Gnu Public licence) de GNU (ce qui signifie que le nom de
son site Internet est tr@`es gödelien...); le texte de cette licence est fourni avec la distribution Enigma:
Si tout ce que vous voulez faire d'Enigma est y jouer (apr@`es tout il est fait pour @,{c}a ! ): Vous ne
voudrez probablement pas lire ladite licence; dans ce cas elle stipule que vous avez le droit de jouer
@`a Enigma, d'y faire jouer vos amis, de le leur distribuer, de le promouvoir !
Si vous voulez contribuer par exemple en @'ecrivant vos propres niveaux (c'est encore le plus fun ! ) il
faut vraiment lire ladite licence ne serait-ce qu'une fois; en r@'esum@'e elle est h@'er@'editaire ce qui vous
oblige @`a l'appliquer @`a vos modifications, et vous interdit par exemple de leur attibuer un caract@`ere
commercial.

@node Le jeu, Objets du jeu, Introduction, Haut
@chapter Le jeu

@menu
* Comment commencer::            Naviguer dans les menus et d@'emarrer une partie
* R@`egles du jeu::                Comment jouer @`a Enigma
* Contr@^oles::                    Raccourcis clavier et souris
@end menu


@node Comment commencer, R@`egles du jeu, Le jeu, Le jeu
@section Comment commencer

Au lancement du jeu, appara@^it le menu principal @`a partir duquel on peut commencer @`a jouer (plut@^ot
facile), quitter le jeu (ceci peut n@'ecessiter une d@'esintoxication...) ou r@'egler des options de jeu. Les
paragraphes suivants expliquent une parties des r@'eglages; le reste se trouve normalement @`a l'usage.

@menu
* Le menu des niveaux::           Choisir un niveau
* Options de jeu::                Adapter Enigma @`a vos pr@'ef@'erences
@end menu


@node Le menu des niveaux, Options de jeu, Comment commencer, Comment commencer
@subsection Le menu des niveaux

En cliquant sur « nouveau jeu » on voit l'@'ecran des paysages qui ressemble @`a ceci:

@image{images/levelmenu,,7cm}

On y voit, en haut, des informations sur le niveau s@'electionn@'e et le chapitre courant, puis au milieu
de l'@'ecran, des repr@'esentations des niveaux disponibles, et en bas des boutons. Pour jouer un des
niveaux, il suffit de cliquer sur le dessin du paysage tel qu'on le voit @`a l'@'ecran, ou d'appuyer sur
« Entr@'ee » d@`es qu'il est s@'electionn@'e; les ascenseurs @`a droite permettent de faire d@'efiler les paysages
du chapitre courant.
Les m@'edailles d'argent repr@'esentent les paysages d@'ej@`a r@'esolus en mode « Facile », les m@'edailles d'or
repr@'esentent les paysages r@'esolus en mode « Normal ». Pour aller directement au prochain paysage
non r@'esolu, un appui sur « F5 » ou un clic sur le bouton repr@'esentant 2 m@'edailles fait l'affaire.
Si jamais les m@'edailles sont accompagn@'ees d'un autre symbole, cela signifie que le niveau a @'et@'e
modifi@'e depuis la derni@`ere fois qu'on y a jou@'e. Les touches suivantes pr@'esentent un int@'er@^et dans cet
@'ecran:
@table @kbd
@item @key{ESC}
Retour au menu principal

@item @key{F1}
Ade en ligne

@item @key{F5}
Aller au prochain niveau non r@'esolu

@item Arrows
S@'election d'un paysage

@item @key{RET}
Jouer le niveau s@'electionn@'e

@item @key{Space}
Aller au chapitre suivant

@item @key{Backspace}
Aller au chapitre pr@'ec@'edent

@end table

@c Au d@'epart, seuls 10 niveaux de chaque chapitre sont jouables.
@c Les autres niveaux sont `cadenass@'es', comme indiqu@'e par le verrou
@c visible sur l'image.  On peut jouer aux niveaux d@'everouill@'es
@c dans n'importe quel ordre, et chaque fois qu'on en a fini un, un
@c des niveaux verrouill@'es se d@'everouille.

Enigma est fourni avec de nombreux niveaux. Vraiment nombreux.  Pour 
s''y retouver, on les a regroup@'es en ``chapitres'':

@itemize @bullet
@item Tutorial
@item Enigma
@item Enigma 2
@item Oxyds
@item Esprit
@item Sokoban
@end itemize

Pour se d@'eplacer dans les chapitres, utilisez les touches @key{Space}
et @key{Backspace} , ou le bouton ``Level Pack''.

@node Options de jeu,  , Le menu des niveaux, Comment commencer
@subsection Options de jeu

Les options du jeu permettent de personnaliser le comportement d'Enigma:


@table @strong
@item Plein Ecran
Alterne entre les modes plein @'ecran et fen@^etr@'e; Alt-Entr@'ee fait pareil

@item Mode Video
Le mode vid@'eo changera lors du retour @`a l'@'ecran principal

@item Vitesse de la souris
Permet de r@'egler la fa@,{c}on dont les mouvements de la souris influencent ceux de la
boule sur l'@'ecran (la masse de la boule); pendant le jeu on peut varier la masse de
la boule avec les fl@`eches gauche et droite.

@item Sauter les niveaux r@'esolus
A la fin d'un niveau, Enigma passe automatiquement au suivant, ou au suivant
non r@'esolu, selon l'@'etat de ce bouton.

@item Chasse au temps
Si ce bouton est appuy@'e, le niveau recommence tout seul si on atteint le meilleur
temps enregistr@'e.

@item Volume bruitages
Permet de r@'egler le volume des effets sonores du jeu.

@item Bruits
Permet de choisir entre les effets d'Oxyd et ceux d'Enigma.

@item Volume musique
R@`egle le volume de la musique de fond.

@c @item Musique pendant le jeu
@c Enigma peut jouer des musiques pendant le jeu.  Ou pas, selon l'@'etat de ce bouton.

@item Stereo
Permet de choisir entre les modes st@'er@'eo et le mode mono.
@end table


@node R@`egles du jeu, Contr@^oles, Comment commencer, Le jeu
@section R@`egles du jeu

@menu
* Paysages normaux::           
* Paysages @`a deux joueurs::       
* Paysages de m@'editation::       
@end menu


@node Paysages normaux, Paysages @`a deux joueurs, R@`egles du jeu, R@`egles du jeu
@subsection Paysages normaux

L'id@'ee de base est assez simple: Vous commandez une boule noire qui doit effleurer dans le bon
ordre des pierres magiques appel@'ees « oxydes », et qui ressemblent @`a ceci:

@image{images/st-oxyds,,0.7cm}

(leur aspect peut varier d'un niveau @`a l'autre).
Chaque fois qu'on touche une oxyde, elle s'ouvre momentan@'ement, r@'ev@'elant une couleur cach@'ee. Ici
le point d'interrogation montre que l'oxyde est ouverte; il s'agit d'une oxyde bleue:

@image{images/intro-oxyd,,3cm}

Si on touche une oxyde d'une autre couleur, la pr@'ecedente se referme. Si on touche une oxyde de la
m@^eme couleur, les deux restent d@'efinitivement ouvertes (du moins jusqu'@`a ce qu'une pierre p@'eteuse
fasse son naus@'eabond office !...); ci-dessus les deux oxydes vertes sont d@'efinitivement ouvertes.
Si on ne peut pas toucher directement une oxyde, on peut utiliser le rayon d'un laser pour ce faire,
mais les lasers d@'etruisent les boules noires !

@emph{Au fait: Si vous n'avez pas encore essay@'e de jouer @`a quelques paysages d'Enigma, le moment est
appropri@'e...!}

Pour ramasser un outil, il suffit de rouler dessus avec la boule noire (elle est tr@`es l@'eg@`ere et d'ailleurs
fragile); en bas de l'@'ecran de jeu on voit l'inventaire des outils actuellement en possession de la
boule noire; l'exemple ci-dessous montre un inventaire o@`u on a une pelle, un document, deux b@^atons
de dynamite, deux vies et un parapluie:

@image{images/intro-inventory,,1cm}

Au d@'ebut du jeu, on poss@`ede deux vies suppl@'ementaires (au cas o@`u il arriverait quelque chose @`a cette
si d@'elicate sph@`ere d'@'eb@`ene). Attention: l'inventaire n'est pas infini !
Un clic sur le bouton gauche permet de d@'eposer, ou d'utiliser selon le cas, l'outil le plus @`a gauche:
Par exemple le b@^aton de dynamite est d@'epos@'e m@`eche allum@'ee, et un ressort fait bondir la boule. Si on
veut utiliser un autre outil que celui qui est @`a gauche, un clic droit r@'earrange les outils dans
l'inventaire. Si pour une raison ou une autre, on souhaite ne pas ramasser un outil en passant dessus
(on ne sait jamais, @,{c}a peut @^etre utile dans certains niveaux), il suffit de laisser le bouton gauche
cliqu@'e en passant dessus.
Certaines pierres sont mobiles (en les poussant assez fort avec la boule noire). Les plus utiles d'entre
elles sont certainement les cubes de bois, qui permettent de construire des ponts au-dessus de zones
interdites aux boules noires, comme les ab@^imes ou, ici, l'eau (la boule noire ne sait pas nager):

@image{images/intro-plank,,4cm}

On y voit la boule noire qui se construit un petit pont de bois, en jetant des cubes de bois dans
l'@'el@'ement liquide.
Certains objets peuvent se transformer, en les @'eclairant avec un laser ou en les @'ecrasant avec des
pierres mobiles; et certaines pierres ont un comportement diff@'erent si on les actionne avec un des
outils de l'inventaire: L'exemple le plus connu est la baguette magique.
Certains objets sont d@'ecrits au chapitre 3.

@node Paysages @`a deux joueurs, Paysages de m@'editation, Paysages normaux, R@`egles du jeu
@subsection Paysages @`a deux joueurs

H@'elas non: Ce n'est pas un jeu en r@'eseau; il n'y a d'ailleurs pas de niveaux avec vraiment deux
joueurs, mais des niveaux @`a un joueur peuvent comporter deux boules pilotables par ledit joueur: La
d@'ej@`a connue boule noire, et une autre qui est blanche; un tel niveau se reconna@^it @`a la pr@'esence d'un
objet en forme de « yin-yang » dans l'inventaire; cet objet permet de choisir laquelle des deux
boules on souhaite piloter:

@image{images/intro-twoplayer,,7cm}


@node Paysages de m@'editation,  , Paysages @`a deux joueurs, R@`egles du jeu
@subsection Paysages de m@'editation

Certains niveaux sont tr@`es particuliers en ce qu'ils n'ont ni boule noire, ni oxydes: Ce sont les
niveaux « meditation ». Ils comprennent de petites boules blanches, @`a caser dans des creux:

@image{images/intro-meditation,,3cm}

d@`es que chaque boule blanche s'est immobilis@'ee dans son propre creux, le niveau est fini. Le nom
de m@'editation vient de ce que souvent, pour les r@'eussir, ces niveaux requi@`erent calme et lenteur...

@node Contr@^oles,  , R@`egles du jeu, Le jeu
@section Contr@^oles

Voici une liste des contr@^oles actifs en phase de jeu (pas besoin de les apprendre par coeur, cette liste
est disponible par un appui sur la touche F1):

@table @kbd
@item clic gauche
Utilisation du premier outil de l'inventaire

@item clic droit/ bouton du milieu
Rotation de l'inventaire des outils

@item @key{Echap}
Retour au menu principal

@item @key{F1}
Affichage de l'aide

@item @key{F3}
Suicide de la boule noire

@item @key{Shift-F3}
Recommence le niveau

@item @key{F4}
Paysage suivant

@item @key{F5}
Prochain paysage non r@'esolu

@item @key{F10}
Prend une photo du paysage

@item @key{Fl@`eche gauche}
Diminuer la vitesse de la souris

@item @key{Fl@`eche droite}
Augmenter la vitesse de la souris

@item Alt-@key{Entr@'ee}
Affichage plein @'ecran ou fen@^etr@'e


@item Alt-X
Retour @`a l'@'ecran des niveaux
@end table

@node Objets du jeu, Triche, Le jeu, Haut
@chapter Objets du jeu

@menu
* Outils::                       
* Pierres::                      
@end menu

@c @node Objets sp@'eciaux,,,
@c @section Objets sp@'eciaux

@c @node Pr@'edateurs,,,
@c @subsection Pr@'edateurs

@node Outils, Pierres, Objets du jeu, Objets du jeu
@section Outils

@menu
* Explosifs::                   Dynamite et bombes
* Parapluies::                   
* Drapeaux::                    Le point de retour
@end menu

@node Explosifs, Parapluies, Outils, Outils
@subsection Explosifs

Il y a trois sortes d'explosifs, que voici du moins dangereux au plus redoutable:

@image{images/it-Explosifs,,0.7cm}

Le b@^aton de dynamite ne d@'etruit que les objets les plus fragiles; son utilit@'e est essentiellement de
mettre le feu aux bombes.
La bombe noire (la plus courante) est suffisamment puissante pour cr@'eer un crat@`ere et d@'etuire les
pierres avoisinantes.
La bombe blanche est thermonucl@'eaire: Elle a la puissance de 5 bombes noires, et peut donc
d@'etruire la boule noire m@^eme si elle n'est pas tr@`es pr@`es: Il y int@'er@^et @`a s'@'eloigner tr@`es vite si elle est
allum@'ee !

@node Parapluies, Drapeaux, Explosifs, Outils
@subsection Parapluies

@image{images/it-umbrella,,0.7cm}

Une fois actionn@'e, le parapluie conf@`ere @`a la boule noire, l'immunit@'e, mais pendant 10 secondes
seulement. Son effet est annonc@'e par un halo blanc autour de la boule noire, constant pendant 7
secondes, puis clignotant pendant les 3 derni@`eres secondes: Ce clignotement signifie donc qu'on est
en fin d'immunit@'e.

@node Drapeaux,  , Parapluies, Outils
@subsection Drapeaux

@image{images/it-Drapeaux,,0.7cm}

Les drapeaux permettent de g@'erer le karma des boules: Normalement si un boule qui a encore des
vies en r@'eserve meurt, elle ressuscite au point de d@'epart du niveau; si on a pr@'ealablement d@'epos@'e un
drapeau quelque part, ce n'est plus le cas: La boule r@'eappara@^it @`a l'endroit du drapeau. La couleur du
drapeau est conforme @`a celle de la boule sur laquelle il agit.

@c @node T@'el@'eporteurs, Elastiques, Drapeaux, Outils
@c @subsection T@'el@'eporteurs

@c @node Elastiques,  , T@'el@'eporteurs, Outils
@c @subsection Elastiques

@node Pierres,  , Outils, Objets du jeu
@section Pierres  

@menu
* Pierres mortelles::               
* Pierres d'@'echange::                 
* Miroirs::                     
* Pierres magiques::                
* Pierres Shogun::               
* Pierres @'electriques::             
* Pierres de puzzle::               
* Pierres postales::                 
@end menu

@node Pierres mortelles, Pierres d'@'echange, Pierres, Pierres
@subsection Pierres mortelles

@image{images/st-lethal,,0.7cm}

Il y a deux sortes de t@^etes de mort: Celle qui est repr@'esent@'ee ci-dessus, et une variante que seules les
boules noires porteuses de lunettes peuvent voir. Au moindre contact, elles tuent les boules.
Le chevalier noir est @'egalement mortel pour les boules d@'esarm@'ees.
Il y a des tueurs mobiles: Les « tops » (toupies) et les « rotors » (croix tournantes); ils sont attir@'es
par leur victime, laquelle a de pr@'ef@'erence une forme sph@'erique et une couleur noire...

@node Pierres d'@'echange, Miroirs, Pierres mortelles, Pierres
@subsection Pierres d'@'echange

@image{images/st-swap,,0.7cm}

En espace ext@'erieur, une pierre d'@'echange est immobile. Mais si on la pousse vers une pierre
adjacente, elle @'echange sa position avec celle de sa voisine, elle est donc utile pour « faire bouger »
des pierres immobiles. Mais elle-m@^eme ne peut @^etre boug@'ee que gr@^ace @`a des pierres « normales ».

@c @node Lasers, Miroirs, Pierres d'@'echange, Pierres
@c @subsection Lasers

@c Both interesting and da

@node Miroirs, Pierres magiques, Pierres d'@'echange, Pierres
@subsection Miroirs

@image{images/st-Miroirs,,0.7cm}

Les mirroirs (@`a droite sur la photo) r@'efl@'echissent les rayons laser, soit en arri@`ere s'ils sont
perpendiculaires @`a ceux-ci, soit @`a angle droit s'ils font un angle de 45° par rapport @`a ceux-ci. Les
prismes (@`a gauche) sont plus complexes: Chaque face agit comme un miroir, mais si le rayon tombe
sur l'angle droit du prisme, il se divise en deux.
Les prismes et miroirs peuvent @^etre soit semi-transparents (aux extr@'emit@'es de la photo; dans ce cas,
le rayon est divis@'e en deux, une partie qui est r@'efl@'echie et une partie qui est transmise) soit opaques
(au milieu de la photo). Ils peuvent @^etre soit mobiles (en les poussant fort avec la boule noire) soit
immobiles. Mais dans les deux cas on peut les orienter en les touchant avec la boule.
La manipulation des prismes et miroirs est dangereuse pour les boules noires si elle est men@'ee pr@`es
d'un laser allum@'e...

@node Pierres magiques, Pierres Shogun, Miroirs, Pierres
@subsection Pierres magiques

@image{images/st-magic,,0.7cm}

Les pierres « magiques » sont un reliquat d'Oxyd et n'ont aucun effet dans Enigma; elles
apparaissent lors de l'importation d'un niveau d'Oxyd et sont cens@'ees dispar@^itre au toucher

@node Pierres Shogun, Pierres @'electriques, Pierres magiques, Pierres
@subsection Pierres Shogun

@image{images/st-shogun,,0.7cm}

Certains niveaux ont des cercles bleus par terre; ceux-ci actionnent quelque chose (ouverture de
porte, allumage de lasers etc.) s'ils sont recouverts par des pierres shogun. Il y a trois sortes de
pierres shogun: La plus petite (@`a gauche sur le portrait de famille) actionne les petits cercles bleus.
Pour les cercles de taille moyenne, il faut r@'ealiser l'empilement que l'on voit au milieu de la photo,
en pla@,{c}ant @emph{d'abord} un shogun de taille moyenne, puis un petit shogun par-dessus. De fa@,{c}on
g@'en@'erale, on ne peut empiler un shogun que sur shogun plus grand que lui, ou sur un sol nu.
Pour les plus grands cercles bleus, il faut r@'ealiser l'empilement de droite en amenant d'abord un
grand shogun, puis en le recouvrant par un shogun moyen, et enfin en recouvrant le tout par un
petit.

@node Pierres @'electriques, Pierres de puzzle, Pierres Shogun, Pierres
@subsection Pierres @'electriques

Le contact avec une pierre charg@'ee @'electrostatiquement, charge un objet, qui porte alors une charge
@'electrique de m@^eme signe que ladite pierre, et est alors repouss@'ee par tous les objets ayant cette
charge, et attir@'e par les objets ayant une charge de signe contraire, du moins @`a courte distance.
Une pierre magn@'etique attire tous les objets.
Une pierre @`a @'elastique attache un @'elastique @`a la boule qui la touche, et tenter de s'en @'eloigner tend
l'@'elastique, ce qui rend l'@'eloignement difficile. Le contact avec une pierre @`a ciseaux coupe
l'@'elastique.

@node Pierres de puzzle, Pierres postales, Pierres @'electriques, Pierres
@subsection Pierres de puzzle

Les puzzles bleus peuvent @^etre assembl@'es, et lorsque l'assemblage est complet (plus de liaison libre),
l'assemblage complet peut bouger, ce qui permet de lib@'erer un chemin, ou de construire des ponts.
Le contact d'un assemblage de puzzles avec une baguette magique d@'etruit l'assemblage s'il est
complet, et permute la position des puzzles sinon.
Les puzzles orange ont le m@^eme comportement sauf qu'il n'y a pas besoin de baguette magique: Il
suffit de toucher l'assemblage avec la boule noire.

@node Pierres postales,  , Pierres de puzzle, Pierres
@subsection Pierres postales

@image{images/st-mail,,0.7cm}

La bo@^ite aux lettres est une pierre en g@'en@'eral prolong@'ee par un tuyau form@'e de puzzles; @`a chaque
contact avec une bo@^ite aux lettres, la boule noire exp@'edie au bout de ce tuyau, l'outil le plus @`a gauche
de son inventaire. Mais une fois qu'un objet autre qu'un puzzle a @'et@'e exp@'edi@'e, la poste est bloqu@'ee.
En g@'en@'eral on doit construire le tuyau en exp@'ediant ses morceaux par la poste.

@c @node Tourniquets, Eboulis, Pierres de puzzle, Pierres
@c @subsection Tourniquets



@c @node Eboulis, Elastiques et ciseaux, Tourniquets, Pierres
@c @subsection Eboulis


@c @node Elastiques et ciseaux,  , Eboulis, Pierres
@c @subsection Elastiques et ciseaux

@node Triche, Cr@'edits, Objets du jeu, Haut
@chapter Triche

Ce chapitre contient des indices pour certains des niveaux les plus difficiles.
On vous conseille vraiment de ne @emph{pas} lire les indices tant que vous n'@^etes pas
compl@`etement bloqu@'es.  Certains niveaux sont vraiment
difficiles (m@^eme les champions d'Enigma ne peuvent les r@'esoudre en moins de quelques heures).
Certains niveaux sont plus faciles en mode « facile » (voir section 2.1.2)

@menu
* Tutoriel::                    Promenade dans 'advanced tutorial'
* Indices::                       Indices pour plusieurs niveaux
@end menu

@node Tutoriel, Indices, Triche, Triche
@section Promenade dans Advanced Tutorial

Cette section a @'et@'e @'ecrite par Jakob Scott, le cr@'eateur des niveaux « tutorial ». Les niveaux du
chapitre « tutorial » sont cens@'es @^etre faciles, @`a l'exception du dernier d'entre eux (« advanced
tutorial »), auquel les paragraphes suivants sont consacr@'es. Premier conseil: Lire tous les documents
de chaque chambre d@`es qu'on y entre.
Le but de ce jeu est donc de trouver, et toucher, toutes les oxydes du niveau, lequel est divis@'e en une
vingtaine de chambres, regroup@'ees en trois zones: La zone 1 est compos@'ee de chambres o@`u on
montre les @'el@'ements de base et certains sols de Enigma. La zone 2 est plus aggressive, avec
l'@'elaboration de strat@'egies parfois destin@'ees @`a @'echapper @`a des ennemis. La zone 3 montre des
interactions plus complexes entre objets Enigma. Dans ce niveau, les oxydes sont regroup@'ees dans
la chambre @`a laquelle on acc@`ede @`a la fin de la zone 3.

@subsection Zone 1

Au d@'epart, on est dans une chambre ferm@'ee par une porte en haut, contenant un peu d'eau en bas @`a
gauche, et un trou dans le mur droit.
Chambre 1: Traverser ce trou pour aller dans la chambre 2.
Chambre 2: Il suffit d'@'eviter les t@^etes de mort pour traverser cette chambre.
Chambre 3: Fabriquer un pont au-dessus de l'eau avec les morceaux de bois; frapper les pierres
noires @`a droite; @'ecarter les pierres mordor@'ees du chemin (par exemple en les poussant vers la
gauche), puis faire un pont vers la droite avec les deux morceaux de bois.
Chambre 4: Aller vers la toupie; quand elle entre en chasse, la mener vers la gauche jusqu'@`a avoir
les pierres centrales entre elle (@`a gauche) et la boule noire; entrer dans la chambre suivante.
Chambre 5: Le seul danger sont les t@^etes de mort du bas: Cette chambre montre certains sols: Dans
l'ordre, le m@'etal a des propri@'et@'es analogues au sol verdoyant vu juqu'ici, le sol rouge frotte plus, la
glace frotte moins et l'espace sid@'eral ne frotte pas du tout, au point qu'il est impossible de changer
de direction quand on le traverse.
Chambre 6: La pente ne pose aucun probl@`eme; aller vers la gauche en utilisant le sol invers@'e (quand
on essaye d'aller vers la gauche, on va vers la droite etc.); au besoin, retourner le mulot peut aider.
Chambre 7: Commencer par gagner une vie suppl@'ementaire en posant la pierre mobile sur la trappe
du bas; la pousser d'abord un carreau vers le haut puis six carreaux vers la gauche; ensuite la pousser 5
carreaux plus bas et 2 carreaux vers la droite; ramasser une autre vie suppl@'ementaire puis actionner
l'autre trappe en y posant la pierre mobile, ce qui ouvre la porte @`a gauche vers la chambre suivante.
Chambre 8: Prendre la dynamite et l'allumer devant les pierres jaunes, ce qui lib@`ere le passage; la
b@^eche n'est pas n@'ecessaire mais on peut exp@'erimenter avec.
Chambre 9: Pousser la pierre mobile la plus basse vers la gauche; les @'eboulis allant vers la droite
bloquent le chemin; en d@'epla@,{c}ant la pierre mobile la plus @`a droite, on laisse l'@'eboulis se produire;
ramasser la baguette magique en faisant attention @`a ne pas encore actionner un @'eboulis avec, puis
pousser la pierre qui est au-dessus de l'eau. Ensuite placer la baguette magique en t@^ete de
l'inventaire pour qu'elle soit active, et s'en servir sur les trois @'eboulis du haut, en faisant attention @`a
ne pas se faire ensevelir; pousser la pierre de gauche pour entrer dans la chambre suivante.
Chambre 10: Actionner l'interrupteur; pousser les deux pierres mordor@'ees dans l'eau; aller vers la gauche;
pousser vers la gauche le bloc de bois du milieu, puis celui qui @'etait juste au-dessus de lui, dans l'eau;
pousser les autres morceaux de bois dans l'eau en une ligne pour fabriquer un pont; d@'efoncer la
fen@^etre @`a grande vitesse (attention aux d@'ebris de verre); r@'ecup@'erer une vie suppl@'ementaire et
traverser le pont de bois jusqu'@`a la premi@`ere chambre; passer par la porte d@'esormais ouverte.

@subsection Zone 2

Dans la zone 2 on rencontre des rotors, qui ne sont pas tr@`es amicaux avec la boule noire; il s'agit de
les amener @`a faire ce qu'on veut leur faire faire tout en s'en pr@'eservant. Jeter un coup d'oeil (sans
bouger pour l'instant la pierre mobile); il s'agit de traverser les trois portes en haut.
Porte 1: Frapper la boule blanche sur la gauche pour lib@'erer celle-ci (attention @`a ne pas traverser le
sens unique noir); ramasser la cuill@`ere puis pousser la boule blanche au travers du sens unique
blanc, suffisamment fort pour qu'elle ne reste pas bloqu@'ee en chemin; maintenant traverser le sens
unique noir et pousser la boule blanche au travers du corridor; la pousser au travers du sens unique
blanc, suffisamment fort pour qu'elle ne reste pas dans le sens interdit. Une fois que la boule
blanche a travers@'e, utiliser la cuill@`ere: On est de retour au d@'ebut du niveau, et plus enferm@'e;
traverser la porte: La premi@`ere des portes du haut est d@'esormais ouverte.
Porte 2: Pousser la pierre mobile qui se trouve @`a droite de la chambre vers la droite, et courir;
un document comportant des informations int@'eressantes devrait @^etre apparu dans la porte qui s@'epare
les zones 1 et 2; amener le rotor (par la m@^eme technique que pour la toupie) au-dessus du mur qui
est @`a droite de la porte; retraverser la porte, puis le pont vers la chambre du bas; actionner
l'interrupteur pour refermer la porte, puis retourner dans la chambre du d@'epart. Longer le mur du
haut de droite @`a gauche pour amener le rotor @`a gauche, puis longer le mur de gauche vers le bas pour
faire descendre le rotor le long du mur gauche, jusqu'@`a ce qu'on ne l'entende plus bouger. Il devrait
avoir actionn@'e une trappe; actionner l'interrupteur pour rouvrir la porte et retourner dans la zone 2:
La porte du milieu devrait @^etre ouverte.
Porte 3: Pousser la pierre mobile qui a servi d'antre au rotor sur la trappe qui se trouve dans la
chambre de d@'epart du rotor; retourner dans la chambre de gauche: La troisi@`eme porte est ouverte.
Traverser les trois portes.

@subsection Zone 3

Chambre 1: Il faut que le rayon du laser atteigne la pierre noire: Pousser le miroir qui est en bas @`a
gauche, d'un carreau vers le bas et le toucher doucement jusqu'@`a ce qu'il soit orient@'e comme ceci:
« \ »; pousser le miroir qui est en haut @`a gauche de 8 carreaux vers la gauche et un carreau vers le
bas, puis l'orienter comme ceci: « / »; pousser le miroir qui est en haut @`a droite de 2 carreaux vers le
haut et 3 carreaux vers la droite, puis l'orienter ainsi: « / ». Actionner l'interrupteur pour allumer le
laser, tout en @'evitant son rayon; quand le pont sur la droite est construit, le traverser vers la droite.
Chambre 2: Ramasser quelques pi@`eces; retourner dans la chambre pr@'ec@'edente; en @'eteignant, puis
rallumant, le laser, irradier avec son rayon, une des pi@`eces de monnaie: Elle se se transforme en
parapluie; ramasser ce parapluie apr@`es avoir @'eteint le laser, puis recommencer avec une autre pi@`ece
pour obtenir un autre parapluie. Poser une pi@`ece @`a c@^ot@'e d'un des miroirs puis pousser ce miroir pour
@'ecraser la pi@`ece; reprendre la pi@`ece et l'irradier avec le rayon du laser pour la transformer en un
marteau. Irradier le marteau avec le laser (en l'@'eteignant puis le rallumant) pour obtenir une @'ep@'ee;
ramasser l'@'ep@'ee. (Au besoin, en @'ecrasant d'autres pi@`eces 2 fois avec les miroirs, puis en @'eclairant les
pi@`eces d'or obtenues avec le laser, on peut obtenir des vies suppl@'ementaires). Remettre les miroirs
dans leur position initiale, puis rallumer le laser, pour pouvoir retourner dans la chambre avec les
chevaliers; y aller. Mettre l'@'ep@'ee en t@^ete d'inventaire puis toucher 4 fois chaque chevalier. On peut
passer.
Chambre 3: Actionner un parapluie pour traverser l'ab@^ime des chambres en bas puis @`a droite; si le
halo clignote, actionner l'autre parapluie.
Chambre 4: Toucher les oxydes dans l'ordre pour les activer, tout en @'evitant les pierres p@'eteuses,
dont l'odeur pestilentielle referme toutes les oxydes.


@node Indices, , Tutoriel, Triche
@section Indices pour plusieurs niveaux

@table @strong

@item I/6: Welcome to the Machine
Le message pr@`es du coin en haut @`a droite contient un indice important.

@item I/8: Easy?
Commencer par placer le premier shogun dans le coin en haut @`a gauche, puis le
deuxi@`eme shogun @emph{au-dessus} du cercle bleu de droite

@item I/31: Where Am I?
Si le petit Poucet n'avait pas de pain, il ramasserait des morceaux de bois. 

@item I/32: The Grim Reaper
C'est une histoire sans queue ni t@^ete: Quelle est la t@^ete d'une souris apr@`es un t@^ete-@`a-queue?

@item I/43: Sokoban Revival
C'@'etait le tout premier niveau du Sokoban originel: Il ne peut donc @^etre si dur !

@item I/65: Lasers 101
Pousser deux miroirs vers le haut et un vers le bas.

@item I/72: Way to Go
L'un des cercles bleus se comporte diff@'eremment.

@item I/80: Meditation
Alignez les boules blanches horizontallement. 

@item II/15: Knock Knock
Ce niveau est @`a se taper la t@^ete dans le mur.

@item II/27: Twelve doors
M@^eme apr@`es avoir ouvert les douze portes, vous ne pouvez toujours pas passer? Vous
avez du rater quelque chose !

@item II/40: Space Meditation
D@'ej@`a entendu parler du probl@`eme des trois corps?

@item II/44: Pharaos' Tombs
Une astuce pour ce niveau se trouve dans ``Easy shifting'.

@item II/56: Easy Shifting...
Une astuce pour ce niveau se trouve dans ``Running Rings''.

@item II/57: Floppy Swapping
Commencer par chercher la disquette et la baguette magique (ils sont n@'ecessaires); 2)
Toujours les garder avec soi; 3) Certaines pierres se ressemblent comme les deux P@^oles
mais sont comme Pierre et Paul.

@item II/59: The Disappearing Block
Encombrez le laser.

@item II/65: Laser Magic
Exp@'erimentez des m@'etamorphoses !

@item II/69: Question of Speed
Qui @emph{s@`eme} le vent r@'ecolte la temp@^ete.

@item II/77: Push Your Way
Commencez par trouver la baguette magique.

@item II/97: Tool Time
Ne mettez pas les outils dangereux @`a la port@'ee des enfants.

@item II/99: Domain of Mysteries
Grimpez pr@'ecautionneusement l'@'echelle.

@item II/100: Patterns
Y a-t-il de l'@'echo?

@item III/9: What's the Problem?
Des leurres partout partout; c'est un niveau de m@'editation.

@item III/14: Use the PIN
Utilisez le code PIN, ou votre encyclop@'edie si vous n'arrivez pas @`a retenir le num@'ero.

@item III/16: Control Panel
Le document de la chambre de gauche vous montre comment arranger les pierres sur les
premi@`eres rang@'ees de trappes; @`a partir de l@`a, utilisez le code de couleurs de la chambre
de gauche. 

@item III/22: Portable Laser
Ne laissez pas le laser vous @emph{griller}!

@item III/27: Tricks and Traps
Pas moyen de quitter le premier @'ecran? Commencez par le petit cercle bleu. Pas moyen
de trouver la derni@`ere oxyde? Activez 3 grands cercles bleus du premier @'ecran et un petit
cercle bleu du troisi@`eme @'ecran.

@item III/28: Wells
Peur de mourir?

@item III/29: Push? Pull!
Un @'echange vers le haut-- Un @'echange vers le bas-- Un puzzle vers la droite-- et on continue!

@item III/40: Snow White
Trois petits eskimos -- Perdus sur la banquise-- 
Ne trouvaient plus leurs igloos -- Enneig@'es par la bise.

@item III/43: The Ditch
Pour r@'esoudre ce niveau, il vous faut briser une vie.

@item III/95: Jump et Run
Un ressort est cach@'e sous un miroir.

@item IV/6: TNT Shortage?
Le marteau est plus utile que la dynamite.

@item IV/17: Flood Gates
Inonder pr@'ecautionneusement certaines zones peut s'av@'erer utile; ne pas quitter la
premi@`ere chambre avant d'avoir actionn@'e l'un des interrupteurs du bas.

@item IV/25: Light Switches
Encombrez les lasers si vous n'@^etes pas assez rapides.

@item IV/27: Robbery
Entrez dans la banque en passant par un sol fragile. 

@item IV/34: Running Rings
Une astuce pour ce niveau se trouve dans ``Pharao's Tomb''.

@item IV/39: How Many Spirals?
Il y a des gens qui sautent par la fen@^etre lors d'un incendie; faites le contraire.

@item IV/47: Just Moving Blocks?
Trop de morceaux de bois? Comment en enlever un?

@item IV/48: Artillery
Le boulet de canon peut aussi servir @`a ouvrir des oxydes.

@item IV/54: Fire Safety
Le trigger vous g@^ene-t-il? D@'etruisez-le!

@item IV/64: The Flagstone Reaper
Il calcule.

@item IV/65: Little Bit of Everything
Utilisez F3.

@item V/15: Solvable?
Est-ce-que WNSE vous @'evoque quelque chose?

@item V/16: Draggers
OK, ce niveau est diabolique. Il y a une graine pr@`es du d@'epart.

@item V/22: Space Pirates
Celui-l@`a est difficile.  Allumez une bombe pr@`es du stock de bois.

@item V/32: Walk the Plank
M@^eme un pirate ne ma@^itrise pas ce niveau?  Il y a un autre chemin, plus facile celui-l@`a.

@item V/34: Island of Safety
Commencez par analyser les centaines.

@item V/45: Psycho Pushing
Frappez et sauvez-vous.

@item V/58: Now What?
Quand vous avez vu la croix, que devrait montrer le r@'eseau ensuite?

@item V/78: Don't Be Greedy
Une aide figure quelque part ailleurs dans ce manuel.

@item V/89: Ice-bombe
Une aide figure quelque part sous l'oxyde.

@item V/91: Firefox
Le sol br@^ule plus vite.

@item V/96: Prepare Your Defense
Le laser ne transforme pas que les outils.

@item VI/7: Orbitting
Ne laissez rien toucher les bords.

@item esprit 43
Faites un sacrifice au volcan.

@item esprit 52
Jouez-le le bon jour.

@item esprit 100
D@'etruisez le coin.

@item Oxyd Magnum 99 (level 22): Letter bomb
Faites un attentat sur les bo@^ites au lettres.

@item PerOxyd 49 (level 22): Hidden Treasure
Assurez-vous un acc@`es @`a la chambre avec l'interrupteur; ensuite cherchez le second
@'ecran avec le ``tr@'esor cach@'e''.

@end table

@node Cr@'edits,  , Triche, Haut
@chapter Cr@'edits

@menu
* D@'eveloppeurs principaux::             
* Special Thanks::              
* Contributeurs::                
* Logiciels utilis@'es::           
@end menu


@node D@'eveloppeurs principaux, Special Thanks, Cr@'edits, Cr@'edits
@section D@'eveloppeurs principaux

@table @strong

@item Siegfried Fennig
Concepteur de niveaux, graphismes

@item Martin Hawlisch
Concepteur de niveaux, graphismes, programmation

@item Daniel Heck
D@'eveloppeur principal, graphismes, documentation

@item Petr Machata
Concepteur de niveaux, programmation

@item Nat Pryce
Concepteur de niveaux

@item Jacob Scott
Concepteur de niveaux

@item Sven Siggelkow
Concepteur de niveaux et connaissances pointues en Oxyd

@item Ralf Westram
Concepteur de niveaux, programmation
@end table


@node Special Thanks, Contributeurs, D@'eveloppeurs principaux, Cr@'edits
@section Special Thanks

@table @strong
@item Johannes Fortmann
Portage sur Macintosh, un peu de programation, graphisme

@item Dustin Norlander
Concepteur de la police “Dustismo”

@item Jeremy Sawicki
Ing@'eni@'erie inverse sur le format des fichiers Oxyd, biblioth@`eque oxylib

@item Erich Schubert
Paquetages Debian

@item Meinolf Schneider
L'id@'ee originale du jeu: @emph{Merci Monsieur Schneider !}

@item Andrew ``Necros'' Sega
Musique du menu (Pentagonal Dreams)


@item David W. Skinner
Beaucoup des niveaux Sokoban; voir @uref{http://users.bentonrea.com/~sasquatch/sokoban}

@end table


@end table

@node Contributeurs, Logiciels utilis@'es, Special Thanks, Cr@'edits
@section Contributeurs

Pour des contributions plus l@'eg@`eres et vari@'ees, citons p@^ele-m@^ele:

@itemize @bullet

@item
Samuel Elï¿½as Martï¿½nez ï¿½lvarez (traduction espagnole)

@item 
Stephanie Fabian (d@'enonciation estimable de bogues)

@item 
Edwin Groothuis (portage sous FreeBSD)

@item
Immanuel Herrmann (conception de niveaux)

@item
Samuele Kaplun (traduction en Italien)

@item
Manuel Kï¿½nig (conception de niveaux, d@'enonciation de bogues)

@item
Jens-Christian Korth (conception de niveaux)

@item
Edward Leuf (d@'enonciation de bogues)

@item
Ingo van Lil (d@'enonciation de bogues)

@item
Frank van der Loo (traduction hollandaise)

@item 
Achim Settelmeier (fichier de sp@'ecification RPM)

@item 
Jon Sneyers (conception de niveaux)

@item
Peter Santo (conception de niveaux)

@item 
Andrzej Szombierski (conception de niveaux)

@item
Michael Terry (fichier .desktop)

@item
Ray Wick (conception de niveaux)

@item
Joe Wreschnig (page Manuel)
@end itemize

@node Logiciels utilis@'es,  , Contributeurs, Cr@'edits
@section Logiciels utilis@'es

@table @strong

@item SDL 
@uref{http://www.libsdl.org/}

@item SDL_image
@uref{http://www.libsdl.org/SDL_image}

@item SDL_mixer
@uref{http://www.libsdl.org/SDL_mixer}

@item Lua
@uref{http://www.lua.org}

@item Oxydlib
@uref{http://www.sawicki.us/oxyd}

@item tolua
@uref{http://www.tecgraf.puc-rio.br/~celes/tolua}

@item zipios
@uref{http://zipios.sourceforge.net}

@end table

@bye
