\input texinfo                              @c -*- texinfo -*-
@afourpaper

@c @include{version.texi}
@set VERSION 1.21

@copying
Copyright @copyright{} 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014 Daniel Heck и другие участники

Копирование и распространение этого файла с изменениями или без разрешено любым
способом без отчислений, если сохранены уведомление об авторских правах и это
уведомление.
@end copying

@setfilename enigma.info
@documentencoding koi8-r
@documentlanguage ru
@settitle Руководство по Enigma
@titlepage
@center @image{images/logo}
@center @titlefont{Руководство по Enigma}
@center для версии @value{VERSION}
@sp 2
@c @center Copyright @copyright{} 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014 Daniel Heck (@email{dheck@@gmx.de})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top, Введение, (dir), (dir)
@top Enigma

Это руководство описывает как установить и играть в Enigma. Оно соответствует
версии Enigma под номером @value{VERSION}.

Copyright @copyright{} 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014 Daniel Heck (@email{dheck@@gmx.de}) и другие участники

Копирование и распространение этого файла с изменениями или без разрешено любым
способом без отчислений, если сохранены уведомление об авторских правах и это
уведомление.
@c @insertcopying
@end ifnottex

@menu
* Введение::                Знакомство с Enigma
* Игра::                    Как играть в Enigma
* Некоторые игровые объекты::           Описание некоторых игровых объектов
* Дополнительные темы::             Дополнительные возможности и администрирование
* Спойлеры::                    Подсказки для некоторых сложных уровней
* Благодарности::                     Создатели и благодарности

@end menu

@node Введение, Игра, Top, Top
@chapter Введение

@menu
* Об Enigma::                       Некоторые факты об Enigma
* Установка::                Получение и установка Enigma
* Распространение Enigma	::         Передавайте копии вашим друзьям!
@end menu


@node Об Enigma, Установка, Введение, Введение
@section Об Enigma

Сказать, что Enigma ? игра-головоломка это преуменьшение. На самом деле Enigma
это огромная коллекция головоломок, и каждый из ее 550 уникальных уровней снова
и снова потребует сообразительности, ловкости и подлинной силы воли от своих игроков.
Enigma проста в изучении, интересна в игре и сложна в овладении. Она может развлечь
пользователей почти любого возраста. Она содержит сотни уровней. И, если этого
не достаточно, она также полностью бесплатна. Если Вам нравятся игры-головоломки
и у Вас твердая рука, Enigma возможно займет Вас на протяжении целых часов.

Цель игры ? найти и открыть пары @samp{Oxyd}-камней одинакового цвета. Просто? Да.
Легко? Конечно, нет! Скрытые ловушки, огромные лабиринты, лазерные лучи и, самое
главное, бесчисленные причудливые головоломки обычно перекрывающие Вам прямой путь
к Oxyd-камням. Игровые объекты Enigma (их здесь сотни, чтобы Вы не скучали)
взаимодействуют многочисленными непредсказуемыми способами, и поскольку многие из
них подчиняются законам физики (а точнее, особым законам физики Enigma), управление
ими с помощью мыши не всегда тривиально @enddots{}

Первоначальная цель проекта Enigma была сохранить дух серии игр Oxyd, после того
как их издатель решил покинуть игровой бизнес в 2002 году. У поклонников этой
знаменитой игры будет чувство дежа вю. Но спустя годы, Enigma впитала идеи из
множества других популярных игр и добавила свои уникальные особенности к каждой
из них.
@c Вы играли когда нибудь в Сокобан?
@c С шахматными конями для передвижения?
@c Почувствуйте дежа вю по отношению к некоторым играм в отдельных уровнях в отдельных,
@c подобных Сокобану самодостаточных пакетах уровней на множестве уровней.

Enigma доступна для Windows, Mac OS X, и большинства разновидностей Linux и других
современных Unix'ов. Она переведена на многие языки. Даже это руководство доступно
на нескольких языках.

Существует официальная @uref{http://www.nongnu.org/enigma, домашняя страница} Enigma,
которая содержит страницы скриншотов, загрузок, последних новостей и самую последнюю
версию этого @uref{http://www.nongnu.org/enigma/manual, руководства}.
С разработчиками Enigma всегда можно связаться с помощью электронной почты по адресу
@email{enigma-devel@@nongnu.org}.

Enigma это свободное программное обеспечение, другими словами, приветствуется
копировать ее и давать ее Вашим друзьям (смотрите (@pxref{Распространение Enigma}).
Enigma разрабатывается маленькой группой добровольцев, все из нас работают в наше
свободное время. Если Вам понравилась игра, пожалуйста пришлите нам электронное письмо.
Это пожалуй единственная вещь, которая всегда приводит к тому, что мы посвящаем этой
игре бесчисленное множество часов.


@node Установка, Распространение Enigma, Об Enigma, Введение
@section Установка

Последняя версия Enigma может быть загружена со
@uref{http://www.nongnu.org/enigma/download.html, страницы загрузок} Enigma. Эта
страница содержит пакеты для следующих операционных систем:

@table @strong
@item Windows
Версия Enigma для Windows распространяется, как самораспаковывающаяся программа.
Просто скачайте и запустите предложенный файл @file{.exe}.

@item Unix
Существуют бинарные пакеты для некоторых популярных дистрибутивов Linux, таких как
SUSE, Redhat или Debian. Для других Unix-подобных операционных систем обычно самое
простое решение это сборка Enigma из исходных кодов.

@item Mac OS X
Для операционной системы версии X установка не требуется, просто запустите файл
@file{.dmg} или @file{.tar.gz}.

@end table

Страница загрузок, как правило, содержит более подробную и современную информацию.
Если Вы не можете заставить Enigma работать на Вашем компьютере, не бойтесь попросить
помощи в рассылке Enigma
(@email{enigma-devel@@nongnu.org}).

@node Распространение Enigma,  , Установка, Введение
@section Распространение Enigma

Enigma это свободное программное обеспечение и она может распространяться на условиях
GNU General Public License (GPL). Эта лицензия поставляется с каждым изданием Enigma
(или в файле @file{COPYING} или в файле
@file{COPYING.txt}).  Если Вы хотите только @emph{играть} в Enigma, Вам не обязательно
читать все те термины (скорее всего Вы и не захотите). Для Вас, лицензия в основном
гласит: Играйте в Enigma сколько хотите, пока хотите и можете давать ее своим друзьям!

Если Вы хотите изменить Enigma или способствовать ее дальнейшей разработке, пожалуйста
@emph{прочтите} ицензию, всего один раз в жизни. Лицензия GPL гарантирует, что Enigma
будет оставаться свободным программным обеспечением в будущем. В частности, если
Вы изменяете Enigma или распространяете измененную версию, Вы не можете отнять ни
у кого другого право использовать, изменять и распространять Enigma или производные
от нее.

Предыдущие два абзаца не заменяют настоящую лицензию, но дают представление о ней
в общих чертах на простом русском. Пожалуйста обратитесь к GPL, если Вы не определились
или если Вам нужно знать больше подробностей.

@node Игра, Некоторые игровые объекты, Введение, Top
@chapter Игра

@menu
* Знакомство::             Передвижение по меню и начало игры
* Правила Игры::           Как играть в Enigma
* Управление::                    Команды клавиатуры и мыши
@end menu


@node Знакомство, Правила Игры, Игра, Игра
@section Знакомство

После запуска Enigma, Вы окажетесь в главном меню, откуда Вы можете начать новую
игру, установить некоторые параметры или выйти из игры, если Вам надоело. Следующие
разделы познакомят Вас с меню уровней и меню настроек; все остальное можно надеятся
говорит само за себя. Многие меню предоставляют интерактивную помощь; просто нажмите
клавишу
@key{F1}.

@menu
* Меню уровней::              Выбирает следующий уровень
* Меню Пакет уровней::         Выбирает пакет уровней
* Настройки::                Приспособьте Enigma под свои предпочтения
* Инспектор уровня::         Подробная информация об уровне
@end menu


@node Меню уровней, Настройки, Знакомство, Знакомство
@subsection Меню уровней

Нажатие на "Начать игру" в главном меню приведет Вас к меню уровней, которое
выглядит приблизительно как это:

@image{images/levelmenu,,7cm}

Экран состоит из трех областей: верхняя область содержит информацию о выбранном
в данный момент уровне и текущем пакете уровней, средняя область показывает вид
доступных уровней, а внизу находится ряд кнопок.

Вы можете передвигаться по списку уровней или используя маленькие кнопки со
стрелками справа, или пользуясь клавишами со стрелками. Для начала новой игры
просто кликните на изображении местности на которой Вы хотите играть или нажмите
@key{Enter}.

В Enigma есть два уровня сложности: "простой" и "нормальный". Чтобы переключиться
между простой и нормальной сложностью, нажмите кнопку в центре ряда кнопок:
переключитесь на значок с изображением серебрянной медали и пера, если Вы предпочитаете
уровни полегче или с изображением золотой медали для нормального, более сложного,
режима игры.

В упрощенной версии доступны не все уровни; поэтому они обозначены пером (если
Вы еще их не решили) или серебрянной медалью в верхнем левом углу их изображения.

Вы можете перейти на следующий уровень нажав или @key{F5}, или кнопку
@key{>>|} в нижнем ряду. Значение слова "следующий" в предыдущем предложении
зависит от режима, который Вы выбрали самой левой кнопкой в нижнем ряду.

@itemize @bullet
@item
Иконка неподвижного черного шарика устанавливается для "строго следующего". Вы
перейдете на следующий уровень в пакете уровней, невзирая на то, решили вы этот
уровень или нет.

@item
@c Планируется: ``готовы к награждению? еще: использовать другой глагол
Иконка показывающая медали, готовые к вручению устанавливается для режима следующего
нерешенного. В этом режиме кнопка @key{>>|} перемещает к следующему нерешенному
уровню.

@item
Иконка с ускоряющимся черным шариком устанавливается для режима соответствия.
Соответствие это профессиональный усредненный рейтинг уровня. Оно представляет
собой очки, которые должны быть набраны опытным игроком. Уровни, в которых ваше
время равно или меньше уровня соответствия будут обозначены значком ускоряющегося
шарика. В этом режиме кнопка
@key{>>|}  перемещает к следующему уровню с очками хуже уровня соответствия.

@item
Наконец, значок планеты предлагает режим охоты за мировыми рекордами. Если Ваши
очки лучшие из всех заработанных, Вы будете удостоены значка мирового рекорда.
Если Вы выберете этот режим, уровень будет переигрываться снова и снова, пока
Вы не добьетесь мирового рекорда.

@c Конечно, мировой рекорд редкое событие. Но Вы можете использовать этот режим в
@c тренировочных целях и чтобы хотя бы немного уменьшить уровень соответствия.
@end itemize

Уровень может дополнительно обозначаться маленьким красным треугольником с
восклицательным знаком в верхнем левом углу. Этот знак уведомит Вас, если уровень
был обновлен после того как Вы его решили. Вы сможете увидеть его только, если
Вы обновите Enigma до более новой версии.

Вы можете перемещаться по меню уровней с помощью следующих клавиш:

@table @kbd
@item @key{ESC}
Вернуться к предыдущему меню

@item @key{F1}
Показать помощь

@item @key{F5}
Перейти к следующему уровню, аналогично кнопке @key{>>|}

@item Стрелки
Сменить уровень

@item @key{Enter}
Играть на выбранном уровне

@item @key{Пробел}
Перейти к следующему пакету уровней

@item @key{Backspace}
Перейти к предыдущему пакету уровней

@end table

@node Меню Пакет уровней, Настройки, Меню уровней, Знакомство
@subsection Меню Пакет уровней

С Enigma поставляется много уровней. На самом деле, много-много уровней. Чтобы
сохранить порядок, они входят в "пакеты уровней". А из-за того, что каждый релиз
Enigma добавляет больше уровней, мы даже собрали пакеты уровней в "группы".
К счастью, все это значительно проще чем звучит.

Чтобы выбрать пакет уровней, войдите в меню "Пакет уровней", которое доступно
из главного меню или из меню уровней.

Это меню показывает группы в левой колонке, а пакеты уровней выбранной группы в
другой колонке справа. Официальными группами, которые поставляются вместе с
Enigma являются следующие:

@itemize @bullet
@item @b{Enigma} - уровни, которые написаны только для Enigma
@item @b{D@'ej@`a-vu} - уровни, которые Вы могли видеть раньше
@item @b{Sokoban}
@item @b{Facets} - специальные наборы и виды выше перечисленных уровней
@item @b{User} - личные уровни и пакеты уровней, наподобие Истории, автоматически
генерируемые системой для пользователя.
@item @b{Development} - шаблоны и незаконченные уровни от команды Enigma
@item @b{All Packs}
@end itemize

Щелчок левой кнопки мыши выбирает группу или пакет уровней.

Описание дополнительных возможностей пакетов уровней смотрите в @ref{Пользовательские пакеты уровней}.

@node Настройки, Инспектор уровня, Меню Пакет уровней, Знакомство
@subsection Настройки

Меню настроек позволяет Вам приспособить Enigma под Ваши предпочтения.

@table @strong
@item Язык
Выберите язык для меню и (если доступно) внутриигровых документов.

@item Полный экран
Переключает между полноэкранным и оконным режимами экрана. Вы также можете использовать
@kbd{Alt-@key{Enter}}, чтобы сделать это, даже когда Вы не в меню настроек.
@emph{Примечание:} На некоторых системах Вы должны вернуться в главное меню,
чтобы переключиться из оконного в полноэкранный режим или наоборот.

@item Видеорежим
Эта кнопка позволяет Вам изменить видеорежим, используемый Enigma. Enigma не
переключает видеорежим немедленно, а ждет пока Вы вернетесь в главное меню.

@item Гамма
Если необходимо, настройте здесь яркость экрана.

@item Скорость мыши
Определяет насколько быстро Ваш шарик ускоряется, когда Вы двигаете мышью.
Вы можете использовать клавиши-курсоры влево и вправо, чтобы изменить скорость
мыши во время игры.

@item Громкость звуков
Громкость звуковых эффектов в игре.

@item Набор звуков
Эта кнопка предоставляет Вам выбор набора звуковых эффектов Enigma, используемых
во время игры. Если Вы используете Enigma с оригинальными файлами данных Oxyd,
эта опция позволит Вам использовать оригинальные звуки на всех уровнях.

@item Громкость музыки
Громкость фоновой музыки в меню.

@c @item Музыка во время игры
@c Enigma может проигрывать музыку во время игры. Включите или выключите эту возможность.

@item Стерео
Переключает между "обычным" стерео, "обратным" стерео и моно звуками.

@item Обновлять рейтинг
Если установлено в @samp{Авто}, Enigma время от времени будет пытаться скачать
новые данные о рейтинге. Это обновит общедоступные рейтинги, мировые рекорды,
очки соответствия и т.п. Смотрите
@xref{Регистрация очков}.

@item Имя игрока
Введите Ваше имя или ник, которые Вы хотите присоединить к вашим рекордам, при
отсылке файла enigma.scores. Смотрите @xref{Регистрация очков}.

@item Папка пользователя
Путь к месту, в котором Enigma хранит все Ваши пользовательские данные. Обратитесь
к справочному руководству за подробной информации.

@item Папка эскизов
Путь к месту, в котором Enigma хранит все Ваши пользовательские эскизы. Обратитесь
к справочному руководству за подробной информацией.

@end table

@node Инспектор уровня, ,Настройки, Знакомство
@subsection Инспектор уровня

Чтобы увидеть более подробную информацию об уровне, Вы можете вызвать инспектора
уровня. Нажмите или просто правую кнопку мыши, или нажмите левую кнопку вместе
с клавишей @key{Ctrl} на изображении уровня в меню уровней.

Вы можете сравнить Ваши очки с мировыми рекордами, очками соответствия, очками
автора уровня. Предусмотрены даже некоторые данные, о том сколько игроков решили
уровень.

Кроме прочей информации, детальное описание которой есть в справочном руководстве,
Вы можете ввести небольшое примечание к уровню и оценить уровень.

Пожалуйста имейте ввиду, что поле для ввода примечания может позволить Вам ввести
только символы ASCII в зависимости от системы с которой работает Enigma.

Рейтинг это ваше личное впечатление от уровня. @samp{-} означает отсутствие мнения.
0 - очень плохой, 5 - посредственный, 10 - самый лучший. Рейтинг будет отослан
вместе с Вашими очками (смотрите (@pxref{Регистрация очков}).

Последнее, но не менее значимое - Вы можете использовать инспектор уровня, чтобы
посмотреть снимки экрана, которые Вы сделали во время игры (смотрите (@pxref{Управление}).

@node Правила Игры, Управление, Знакомство, Игра
@section Правила Игры

@menu
* Обычные местности::
* Местности для двух игроков::
* Местности для медитации::
@end menu


@node Обычные местности, Местности для двух игроков, Правила Игры, Правила Игры
@subsection Обычные местности

Основная идея Enigma проста: В большинстве уровней Вы управляете маленьким черным
шариком, ищете и "открываете" совпадающие пары так называемых @emph{Oxyd-камней}.
Закрытые Oxyd-камни выглядят как эти (существует четыре различных варианта, но
все они действуют одинаково):

@image{images/st-oxyds,,0.7cm}

Когда Вы касаетесь Вашим шариком Oxyd-камня, он открывается и показывает обозначение
цвета. На любой местности есть два Oxyd-камня с одинаковым обозначением. Вы должны
дотронуться до двух соответствующих камней подряд, чтобы открыть их навсегда---если
символы не одинаковы, первый Oxyd-камень снова закроется. Чтобы завершить местность
Вам нужно найти и открыть все пары Oxyd-камней. На следующем изображении Вы видите
пару зеленых Oxyd-камней, которые уже открыты. Знак вопроса внутри синего Oxyd-камня
означает, что второй синий символ остается спрятанным.

@image{images/intro-oxyd,,3cm}

@emph{Между прочим: если Вы еще не сделали этого, сейчас самое время запустить
Enigma и поиграть на первых уровнях!}

Вы можете поднимать с пола объекты передвигаясь по ним. Инвентарь внизу экрана
показывает список предметов в вашем распоряжении. В начале новой игры у Вас не
будет ничего, кроме двух запасных шариков. Следующее изображение показывает
инвентарь, содержащий лопату, клочок бумаги, два бруска динамита, Ваши дополнительные
жизни и зонт:

@image{images/intro-inventory,,1cm}

Самый левый объект может быть активирован нажатием левой кнопки мыши: он будет
или брошен на пол, или выполнит какое-то действие. Динамит, например, загорится,
когда Вы бросите его, а пружина подбросит Ваш шар. Нажмите правую кнопку мыши или
используйте колесо мыши, чтобы чередовать предметы в инвентаре.

Если, по какой-то причине, Вы не хотите поднимать предметы, зажмите любую кнопку
мыши, когда передвигаетесь. В некоторых ситуациях это может Вам пригодится.

Многие камни могут перемещаться, если достаточно сильно их толкнуть. Один из
самых полезных камней ? деревянный ящик, который используется для строительства
мостов через воду и бездну. Это изображение показывает как строить мост, сбрасывая
деревянные ящики в воду:

@image{images/intro-plank,,4cm}

Игровые объекты взаимодействуют друг с другом удивительными способами: объекты
лежащие на полу, например, могут быть преобразованы, с использованием лазерных
лучей и подвижных камней. А многие камни изменяются, если Вы коснетесь их различными
объектами из первого слота Вашего инвентаря (волшебная палочка-?-самый известный
объект в этой категории).

Последнее, но не менее значимое: Не впадайте в уныние от видимой запутанности
игры---поведение большинства объектов в свое время станет ясным. Некоторые
неясные объекты описаны в @ref{Некоторые игровые объекты}.

@node Местности для двух игроков, Местности для медитации, Обычные местности, Правила Игры
@subsection Местности для двух игроков

Сначала немного о плохом: Enigma еще не поддерживает Интернет или сетевую игру.
Поэтому, местности для двух игроков в действительности однопользовательские,
где Вы можете переключаться между двумя шарами: черным, которым Вы уже пользовались
и дополнительным белым шаром:

@image{images/intro-twoplayer,,7cm}

На то, что Вы на уровне для двух игроков указывает маленький символ Инь-Янь в
Вашем инвентаре. Активация этого объекта переключает управление с черного на
белый шар и наоборот.

@node Местности для медитации,  , Местности для двух игроков, Правила Игры
@subsection Местности для медитации

В так называемых местностях для медитации Ваша задача совершенно другая: в отличие
от нахождения совпадающих Oxyd-камней, Вам нужно положить все маленькие белые
шарики в лунки в полу. Уровень завершится, как только каждый шарик
@emph{остановится} в своей собственной лунке.

@image{images/intro-meditation,,3cm}

Однако будьте осторожны: Все шарики передвигаются вместе и поспешное движение
мышью может легко вытолкнуть некоторые из них из своих лунок. Местности для
медитации, как правило, требуют очень твердой руки и уйму терпения (между прочим,
именно поэтому они называются местностями для медитации!).

@node Управление,  , Правила Игры, Игра
@section Управление

Здесь перечислено управление во время игры. (Вы не обязаны запоминать его прямо
сейчас?-Вы всегда можете отобразить этот список во время игры, нажав клавишу
@key{F1}.)

@table @kbd
@item Левая кнопка мыши
Использовать первый предмет в инвентаре

@item Правая кнопка мыши/колесо мыши
Чередовать предметы инвентаря

@item @key{ESC}
Показать игровое меню

@item @key{F1}
Показать экран помощи

@item @key{F3}
Уничтожить текущий шар

@item @key{Shift-F3}
Перезапустить текущий уровень

@item @key{F4}
Перейти к следующему уровню

@item @key{F5}
Перейти к следующему нерешенному уровню

@item @key{F10}
Сделать снимок экрана

@item @key{Стрелка влево}
Уменьшить скорость мыши

@item @key{Стрелка вправо}
Увеличить скорость мыши

@item Alt-@key{Enter}
Переключиться между полноэкранным и оконным режимом (не на всех системах работает
незамедлительно)

@item Alt-X
Немедленно вернуться к меню уровней
@end table

@node Некоторые игровые объекты, Дополнительные темы, Игра, Top
@chapter Некоторые игровые объекты

Существуют дюжины различных игровых объектов, которые Вы увидите на уровнях Enigma.
Мы хотим описать здесь только небольшой классифицированный набор этих объектов.
Если Вы новенький в Enigma, возможно Вы захотите начать с уровней из пакета учебника?
Просто запустите Enigma, выберите "Пакет уровней", потом кнопку "Enigma" в верхнем
левом углу, потом "Tutorial" справа. Начните с первого уровня "Oxyd Stones 1".
Учебник покажет Вам самые важные объекты и идеи, и некоторые из простейших уровней
Enigma.

@menu
* Предметы::
* Камни::
@end menu

@c @node Специальные объекты,,,
@c @section Специальные объекты

@c @node Хищники,,,
@c @subsection Хищники

@node Предметы, Камни, Некоторые игровые объекты, Некоторые игровые объекты
@section Предметы

@menu
* Взрывчатка::                  Динамит и бомбы
* Зонты::
* Флаги::                       Установка точки восстановления
@end menu

@node Взрывчатка, Зонты, Предметы, Предметы
@subsection Взрывчатка

@image{images/it-explosives,,0.7cm}

Существует три типа взрывчатки, которые Вы можете найти повсюду в Enigma. Самый
безобидный это палочка динамита. Она наносит не такой большой урон поверхности
или соседним камням, когда взрывается, но она полезна для разрушения определенных
камней и для поджигания соседних бомб.

Черные бомбы достаточно мощные, чтобы разрушить большинство поверхностей и многие
другие объекты. Для большинства целей они--выбор для разрушения. У белых бомб
сила разрушения пяти черных бомб, убегайте скорее, когда увидите их горящими!

@node Зонты, Флаги, Взрывчатка, Предметы
@subsection Зонты

@image{images/it-umbrella,,0.7cm}

Используйте зонты, чтобы сделать Ваш шар неуязвимым на небольшой момент времени
(десять секунд, если быть точным). Когда Вы активируете зонт, вокруг вашего шара
появится белый ореол на время действия защиты. Если ореол начал мигать, у Вас
есть три секунды, чтобы переместить Ваш шар в безопасное место.

@node Флаги,  , Зонты, Предметы
@subsection Флаги

@image{images/it-flags,,0.7cm}

Флаги в основном используются в длительных и опасных путешествиях. Если Ваш шар
разрушился, новый шар появится на том месте, где Вы в последний раз установили
флаг, вместо того чтобы появиться в начале уровня. Есть два типа флагов: черный
и белый, которые устанавливают начальные точки соответственно черного и белого шаров.

@c @node Телепорты, Эластичная лента, Флаги, Предметы
@c @subsection Телепорты

@c @node Эластичная лента,  , Телепорты, Предметы
@c @subsection Эластичная лента

@node Камни,  , Предметы, Некоторые игровые объекты
@section Камни

@menu
* Смертоносные камни::
* Обменные камни::
* Зеркала::
* Односторонние камни::
* Сегун-камни::
* Болдеры::
* Камни-мозаики::
* Почтовые камни::
@end menu

@node Смертоносные камни, Обменные камни, Камни, Камни
@subsection Смертоносные камни

@image{images/st-lethal,,0.7cm}

Существует два вида камней, которых Вы должны избегать во что бы то ни стало,
только если у Вас нет зонта, чтобы защитить Ваш драгоценный шарик.

@emph{Камень с изображением черепа} так же опасен, как и выглядит; дотроньтесь
до него и погибнете. На самом деле Вы предупреждены. Существуют даже более хитрые
варианты, которые невидимы; не забудьте Ваши магические очки.

@emph{Черный рыцарь} часто охраняет важные проходы, и в основном он @emph{не} в
настроении пропускать Вас. Предъявите хороший аргумент, чтобы "убедить" его.

@node Обменные камни, Зеркала, Смертоносные камни, Камни
@subsection Обменные камни

@image{images/st-swap,,0.7cm}

Обменные камни, будучи ударенными, не просто перемещаются на смежный (пустой)
участок; вместо этого, они меняются местами с камнем который они ударили.
Следовательно, единственный способ переместить обменный камень из одного места
в другое---неоднократно менять его с другими "обычными" камнями.

@c @node Лазеры, Зеркала, Обменные камни, Камни
@c @subsection Лазеры

@c Both interesting and da

@node Зеркала, Односторонние камни, Обменные камни, Камни
@subsection Зеркала

@image{images/st-mirrors,,0.7cm}

Лазерные лучи могут преломляться с помощью зеркальных камней. В Enigma существует
два типа зеркальных камней: плоские зеркала и треугольные зеркала. Плоское зеркало
ведет себя как обычное зеркало: входящий лазерный луч отражается, если он
перпендикулярен зеркалу и отклоняется влево или вправо, если он падает на зеркало
под углом в 45 градусов.

Треугольные зеркала немного сложнее: три стороны ведут себя как обычные зеркала,
отражая и отклоняя входящий луч. Но луч, который падает на вершину треугольника
разделяется на @emph{два} исходящих луча, которые движутся в противоположных направлениях.

Оба типа зеркал дополнительно могут быть полупрозрачными или перемещаемыми.
Полупрозрачные зеркала преломляют часть входящего луча, как их непрозрачные
братья, но часть луча проходит неизменной. Перемещаемые зеркала смонтированы
на светло-серые камни, неподвижные на темно-серые камни.

Вы можете поворачивать зеркала, слегка дотрагиваясь до них своим шаром. Но будьте
осторожны с зеркалами, на которые уже падает лазерный луч, довольно просто
неумышленно уничтожить Ваш шар!

@node Односторонние камни, Сегун-камни, Зеркала, Камни
@subsection Односторонние камни

@image{images/st-oneway,,0.7cm}

Через эти камни можно пройти только в одном направлении. Из них могут быть построены
целые лабиринты, но в основном они вынуждают Вас закончить одну часть уровня, перед прохождением следующей.

У Вас проблемы с односторонним камнем, который преграждает Вам путь? Может быть
волшебный предмет сможет Вам помочь @enddots{}

@node Сегун-камни, Болдеры, Односторонние камни, Камни
@subsection Сегун-камни

@image{images/st-shogun,,0.7cm}

В некоторых уровнях Вы можете встретить мигающие синие точки на поверхности.
Они могут быть активированы правильной комбинацией @emph{сегун-камней}, тогда
они обычно сделают что-то полезное, наподобие открытия дверей или создания мостов.

Маленькая мигающая точка активируется перемещением на нее сегун-камня с маленьким
отверстием. Чтобы активировать большие точки, одного сегун-камня недостаточно.
Вместо этого Вам нужно правильно сложить два или три сегун-камня, вталкивая камни
с маленькими отверстием в камни с большими отверстиями. Например, если Вы хотите
активировать точку среднего размера, Вам нужно сначала разместить на ней сегун-камень
с отверстием средних размеров, а потом втолкнуть камень с малым отверстием в тот,
что больше.

@node Болдеры, Камни-мозаики, Сегун-камни, Камни
@subsection Болдеры

@image{images/st-bolder,,0.7cm}

Болдеры движутся в направлении, показанном на них стрелкой, пока не столкнутся с
другим камнем. Возможно они блокируют Вам путь и Вам надо освободить их тем или
иным способом. Но никогда, никогда не становитесь перед ними, так как Ваш шар
мгновенно разобьется, когда болдер пройдет по нему!

Однако, Вы также можете использовать их, так как они способны открывать Oxyd-камни,
когда столкнутся с ними. Вы можете перенаправить целенаправленные камни несколькими
способами @enddots{}

@node Камни-мозаики, Почтовые камни, Болдеры, Камни
@subsection Камни-мозаики

@image{images/st-puzzles,,0.7cm}

Камни-мозаики получили свое имя из-за того, что отдельные камни могут быть соединены
вместе, как кусочки мозаики. У камней-мозаик есть разъемы на некоторых или на всех
сторонах, которые могут прикрепляться к разъемам смежных камней. Как только они
будут соединены, группы камней-мозаик перемещаются как единое целое. Вы можете
использовать эти блоки, например, чтобы строить мосты через воду или бездну.

Когда их коснется волшебная палочка, камни-мозаики отреагируют по разному. Если
блок камней-мозаик соединен окончательно (другими словами у него нет свободных
разъемов), блок немедленно начнет взрываться, камень за камнем. Если блок соединен
не до конца, камни в ряду или колонке, до которой дотронулись сместятся на одно
место по горизонтали или по вертикали.

Существует редкий вариант обычных камней-мозаик, который ведет себя немного по
другому. Основная его среда обитания это уровни Oxyd 1, а узнать его можно по
цвету труб, оранжевому вместо синего. Эти камни-мозаики не могут перемещаться
как единое целое. Они ведут себя как синие камни-мозаики, когда Вы дотрагиваетесь
до них волшебной палочкой: блок взрывается, если он полностью соединен или ряд
или колонка блока, до которой дотронулись смещается.

@node Почтовые камни,  , Камни-мозаики, Камни
@subsection Почтовые камни

@image{images/st-mail,,0.7cm}

Почтовые камни могут использоваться для пересылки предметов из Вашего инвентаря
в некое недоступное место на поверхности. Когда Вы дотрагиваясь используете почтовый
камень, первый объект в Вашем инвентаре изымается и ложится в конце канала связи,
присоединенного к почтовому камню. В большинстве случаев, Вы должны сами построить
этот канал, например, "пересылая" отдельные части канала.

Будьте осторожны: почтовый камень не работает, если на конце канала связи уже
есть объект. Очень легко неумышленно переслать объект, который впоследствии
заблокирует канал, поэтому будьте осторожны!

@c @node Турникеты, Болдеры, Камни-мозаики, Камни
@c @subsection Турникеты



@c @node Болдеры, Резинки и ножницы, Турникеты, Камни
@c @subsection Болдеры


@c @node Резинки и ножницы,  , Болдеры, Камни
@c @subsection Резинки и ножницы

@node Дополнительные темы, Спойлеры, Некоторые игровые объекты, Top
@chapter Дополнительные темы

@menu
* Пользовательские пакеты уровней::            История, Результаты поиска и Авто
* Резервное копирование::                      Что копировать для безопасности
* Регистрация очков::          Позвольте миру узнать о Вашем успехе
* Обновление Enigma::             Сохранение очков и уровней при обновлении
@end menu

@node Пользовательские пакеты уровней, Резервное копирование, Дополнительные темы, Дополнительные темы
@section Пользовательские пакеты уровней

@ref{Меню Пакет уровней} предлагает некоторые дополнительные возможности. В группе
@samp{User} есть три пакета уровней, которые изначально пусты:
@samp{Auto Folder}, @samp{History} и @samp{Search Result}.

Кликая на кнопке @samp{Поиск} в меню пакетов уровней Вы можете искать среди
совокупности уровней. Просто переместите мышь к текстовому полю и введите
строку для поиска. Вы можете искать по автору, названию и имени файла. Поиск не
восприимчив к регистру. Например, Вы можете искать строку "jump". Полученные
уровни будут представлены в пакете уровней под названием "Search Results".

Пакет уровней @samp{History} обновляется автоматически с каждым уровнем на котором
Вы играли. Это может пригодиться, если Вы ищете уровень, на котором играли на
последней неделе, но не знаете ключевых слов для поиска.

@samp{Auto Folder} это пакет уровней, который Вы можете использовать, чтобы
добавить новые уровни, например уровни, которые Вы скачали из Интернета или
написали сами. Папка, в которой Вы должны хранить уровни---@samp{levels/auto} в
директории, которая указана в строке @samp{Папка пользователя} в
@ref{Настройки}. Когда Enigma запускается, уровни в этой папке находятся и
загружаются автоматически.

Enigma предлагает намного больше возможностей, выходящих за пределы этого руководства.
Чтобы узнать подробности, пожалуйста прочтите справочное руководство.

@node Резервное копирование, Регистрация очков, Пользовательские пакеты уровней, Дополнительные темы
@section Резервное копирование

Если Вы боитесь потерять все Ваши очки, в результате отказа жесткого диска, или
если Вы хотите переместить Ваши очки с одного компьютера на другой, полезно знать,
как зарезервировать информацию о состоянии Enigma. Чтобы сделать это, сначала
найдите в @ref{Настройки} Enigma
@samp{Папку пользователя}.  Вы можете просто сделать резервную копию той папки
---важными являются файлы @samp{enigma.score} и @samp{state.xml}.

@node Регистрация очков, Обновление Enigma, Резервное копирование, Дополнительные темы
@section Регистрация очков

Для регистрации Ваших очков, Вам нужно отправить нам файл @samp{enigma.score},
расположенный в директории @samp{Папка пользователя}. Пожалуйста ищите более
подробные указания на домашней странице проекта.

Чтобы автоматически скачивать списки обновленных мировых рекордов, Вам просто
нужно включить опцию @samp{Обновлять рейтинг}.

@node Обновление Enigma, , Регистрация очков, Дополнительные темы
@section Обновление Enigma

Если Вы не настраивали Вашу старую версию, просто удалите старую версию и установите
новую. Это все, что Вы должны сделать, так как Ваши очки автоматически обновятся.

Если Вам понадобится добавить уровни в директории установки Enigma, Вам нужно
сделать их резервную копию перед удалением. После этого Вы можете без опасений
удалить старую версию и установить новую.

@c Планируется: слишком сложно (HOMEless, переменная окружения)@item
@c Планируется: разделить на два предложения
Старый файл очков @samp{~/.enigmarc2} для систем с переменной окружения @samp{HOME}
или @samp{.../Application Data/enigmarc.lua2} для лишенных "HOME" систем Windows
автоматически преобразуется в новый формат. Вы можете удалить старые очки после
первого успешного запуска Enigma 1.00.

Если Вы хотите играть на уровнях, которые Вы сохранили со старой установки,
пожалуйста прочтите справочное руководство.

@node Спойлеры, Спойлеры, Дополнительные темы, Top
@chapter Спойлеры

Этот раздел содержит подсказки для некоторых сложных уровней. Настоятельно @emph{не}
рекомендуется читать спойлеры, если Вы не застряли окончательно. Некоторые уровни
намеренно усложнены и даже игрокам-ветеранам Enigma нужны часы, чтобы решить их.
Некоторые уровни легче решить в упрощенном режиме игры (смотрите (@pxref{Меню уровней}).

@menu
* Учебник::                    Прохождение Advanced Tutorial
* Советы::                       Советы для нескольких уровней
@end menu

@node Учебник, Советы, Спойлеры, Спойлеры
@section Прохождение Advanced Tutorial

Считается, что местности в пакете уровней "Tutorial" просты. Кроме последней,
которая не так проста @enddots{}  Этот раздел руководства предоставлен Jacob Scott.

Это прохождение моего уровня "Advanced Tutorial" в пакете уровней "Tutorial"
(чтобы менять пакеты уровней, кликните на "Пакет уровней" внизу-слева экрана и
выберите пакет уровней). Во время игры в первую очередь, Вам нужно читать все
документы в комнате.

Конечная цель этого уровня, как и большинства уровней Enigma, найти и дотронуться
до всех "Oxyd-камней" своим черным шариком. Когда Вы касаетесь Oxyd-камня, он
открывается и показывает цвет. Если Вы дотронетесь по очереди до двух Oxyd-камней
одинакового цвета, они оба останутся открытыми. Вы завершите уровень, как только
подберете все пары Oxyd-камней на уровне.

В уровне около двадцати комнат, собранных в три отдельных области. В первой области
Вы встретите некоторые основные типы блоков и поверхностей, которые встречаются
в Enigma и решите пару простых головоломок. Вторая область сложнее и познакомит
Вас с полезными приемами обмана активного врага. Третья и последняя область даст
Вам поэкспериментировать с продвинутым взаимодействием между объектами Enigma. В
этом отдельном уровне, всевозможные камни могут быть найдены в одной комнате в
конце третьей области.

@subsection Область 1

Вы начинаете в комнате окруженной неподвижными стенами, кроме прохода справа,
воды внизу-слева и закрытого прохода вверху-справа.

Комната 1: Идите через проход в стене справа.

Комната 2: Просто избегайте блоков с изображенным на них черепом.

Комната 3: Столкните четыре деревянных ящика в воду в ряд, чтобы создать мост
на противоположный берег. Теперь толкните черноватые блоки справа. Передвиньте
блоки из коры с пути (возможно влево) и постройте мост справа из деревянных ящиков.

Комната 4: Подойдите поближе к волчку. Когда он погонится за Вами, ведите его
влево и вокруг блоков в центре комнаты. Как только волчок будет далеко от перехода
на следующий уровень, проскочите туда.

Комната 5: Единственная опасность здесь---черепа внизу комнаты. Первый тип
поверхности это металл---эта поверхность похожа на "лиственную", по которой Вы
передвигались ранее. Следующая поверхность "красная"---на этой поверхности сложно
замедлиться или ускориться. Третий тип это лед---на этой поверхности слабое трение.
Последний тип поверхности это космос---здесь вообще нет трения; вы не можете изменить
вектор скорости (скорость и направление), когда Вы находитесь на этой поверхности.

Комната 6: Просто идите по склонам. Потом выйдите влево, пройдя по "обратной"
поверхности---когда на этой поверхности Вы направляете мышь (или похожий контроллер)
в одном направлении, шар ускоряется в обратном (если у Вас с этим проблемы,
попробуйте повернуть Вашу мышь на 180 градусов).

Комната 7: Попытайтесь получить дополнительный шар, поставив подвижный блок на
нижний переключатель. Сначала толкните его на один квадрат вверх, потом влево
на шесть квадратов. Потом толкните его на пять квадратов вниз и два вправо. В
конце концов толкните его на один квадрат вверх и один влево. Возьмите дополнительный
шар и затем поставьте блок на другой переключатель, чтобы открыть проход слева
от комнаты.

Комната 8: Возьмите динамит (Вам нужно будет зайти на лед) и бросьте его напротив
желтых блоков, чтобы взорвать их и пройти. Лопата не обязательна, но останьтесь
поэкспериментировать с ней.

Комната 9: Толкните самый нижний подвижный блок влево. Сейчас болдеры, пытающиеся
пройти вправо, преграждают Вам путь. Толкните самый правый подвижный блок (влево
или вправо), чтобы дать сползти болдерам. Возьмите волшебную палочку (не дотрагивайтесь
случайно ни до каких подвижных блоков, когда волшебная палочка находится в начале
Вашего инвентаря) и толкните подвижный блок над водой вниз. Теперь вернитесь в
правую часть комнаты, выставьте волшебную палочку в начало Вашего инвентаря и
коснитесь трех верхних болдеров из длинного столбца (постарайтесь не попадаться
на пути любых болдеров). Толкните самый левый подвижный блок влево и идите в
следующую комнату.

Комната 10: Коснитесь переключателя. Теперь толкните два блока из коры вверх (на
один квадрат каждый). Толкните средний (сверху вниз) деревянный ящик влево, а
деревянный ящик, справа-сверху от него в воду. Столкните оставшиеся ящики в воду,
чтобы образовать столбец (постарайтесь не утонуть). Теперь ударьте окно (голубую
полосу) на большой скорости. Возьмите шар и перейдите через мост в первую комнату.
Отсюда идите в открывшийся проход.

@subsection Область 2

Во второй области Вы встретите ротор, являющийся активным противником Вашего
черного шара. Различные роторы могут действовать несколько различно, но они
всегда непонятливы. Предназначение последнего---заставить его сделать, то что
Вам нужно, держась на безопасном расстоянии.

Осмотритесь в этой области (но пока не трогайте подвижный блок). Вам нужно
пройти через трое закрытых ворот в верху этой области.

Первые ворота: Толкните белый шар влево (не пройдите случайно через черный
односторонний блок) чтобы освободить его (это может потребовать нескольких
попыток). Возьмите ложку и довольно сильно толкните белый шар через белый
односторонний блок, чтобы он не остановился. Теперь идите через черный односторонний
блок и проведите белый шар через проход. Довольно сильно толкните белый шар через
следующий белый односторонний блок, чтобы он не остановился ниже. Как только белый
шар пройдет, используйте ложку; Вы вновь начнете уровень в начале и больше ничего
не случится. Снова пройдите через ворота---первые ворота вверху комнаты открыты.

Вторые ворота: Толкните подвижный блок в самой правой комнате этой области вправо
и бегите. В воротах, соединяющих вторую и третью область, появится документ с
полезной информацией. Подведите ротор (заставляя его гнаться за Вами, как Вы
делали это с волчком) к низу стены справа от ворот между первой и второй областями.
Пройдите через ворота и через мост в комнату под Вами. Коснитесь переключателя,
чтобы закрыть ворота и вернитесь в комнату откуда Вы начали. Вы больше не видите
ротор---его не будет в той комнате, где и Вы---но если присмотреться, Вы сможете
увидеть где он. Цель здесь состоит в том, чтобы не подвергая себя опасности, заставить
ротор пойти к переключателю и открыть для Вас дверь. Пусть ротор пойдет за Вами из
верхнего-правого угла этой комнаты в верхний-левый. Он должен быть вытолкнут влево
несколькими наклонами. Доведите ротор вниз слева, пока он не продолжит свой путь и
Вы не услышите звук нажатого переключателя. Коснитесь переключателя, чтобы открыть
ворота и вернуться во вторую область ? вторые ворота, должны быть открыты.

Третьи ворота: Просто толкните подвижный блок, из которого выскочил ротор, на
переключатель в комнате, где он появился. Вернитесь в комнату слева от Вас---третьи
ворота должны быть открыты. Идите через трое отрытых ворот.

@subsection Область 3

В третьей области Вам нужно исследовать взаимодействия между различными объектами
Enigma. Здесь Вы найдете лазеры, зеркала и монеты. Вам прийдется решить простую
головоломку лазер-и-зеркало, чтобы дать лазеру попасть в отдельный камень, который
откроет мост в следующую комнату. Чтобы преодолеть следующие несколько комнат,
Вы должны создать несколько новых объектов, прожигая лазерным лучом существующие
объекты.

В первой части этой области есть три зеркала и лазер с переключателем.

Комната 1: Вам нужно дать лазеру попасть в черный камень. Толкните нижнее-левое
зеркало на один квадрат вниз и поверните его так, чтобы оно выглядело наподобие
"\" легко дотрагиваясь до него (влево вплоть до лазера должно быть тридцать
квадратов). Толкните верхнее-левое зеркало на восемь квадратов влево, на один
квадрат вниз и поверните его, чтобы оно было похоже на "/" (оно должно быть в
четырех квадратах от предыдущего зеркала и прямо над ним). Толкните верхнее-правое
зеркало на два квадрата вверх, а затем на три квадрата вправо (оно должно быть
правее на двадцать два квадрата от предыдущего зеркала и на один квадрат ниже
черного камня). Расположите это зеркало в виде "/". Теперь дотроньтесь до переключателя,
чтобы включить лазер (не попадите под него или не проходите через лазерный луч).
Как только это будет сделано, идите через мост справа от Вас.

Комната 2: Возьмите несколько монет и возвращайтесь в предыдущую комнату. Выключив
и включив лазер, поразите лазерным лучом одну из монет. Возьмите полученный объект
(зонт), повторите процесс и возьмите второй зонт. Теперь бросьте одну из монет за
зеркалом и сдвиньте на нее зеркало. Поразите эту монету со значением пять лазером,
чтобы создать молот. Поразите лазером молот (выключив и включив лазер), чтобы создать
меч. Если Вы хотите несколько дополнительных шаров, Вы можете перетащить зеркало над
монетой дважды и поразить лазером монету с увеличенным значением (самое большее,
до десяти). Чтобы вернуться в комнату с рыцарями, поставьте зеркала в их начальные
позиции, уберите все объекты, блокирующие лазер и коснитесь переключателя. Теперь
используя правую кнопку мыши или клавишу "Tab" выставьте в начало (слева) своего
инвентаря меч. Ударьте несколько рыцарей (каждого по четыре раза), чтобы пройти.

Комната 3: Используйте зонт и проследуйте над бездной в комнату под Вами, а
затем в комнату справа от Вас. Если окружающее Вас кольцо начнет мигать,
используйте другой зонт.

Комната 4: Просто подберите пары Oxyd-камней дотрагиваясь до Oxyd-камней
одинакового цвета с активированными Oxyd-камнями (по одному за раз). Не трогайте
грубые камни (черные камни). Вы выиграли!


@node Советы,  , Учебник, Спойлеры
@section Советы для нескольких уровней

@table @strong

@item I/6: Welcome to the Machine
Сообщение вблизи верхнего-правого угла содержит важный совет.

@item I/8: Easy?
Поставьте первый сегун-камень в верхний левый угол, а второй @emph{над} самой
правой сегун-точкой.

@item I/31: Where Am I?
Используйте деревянные ящики, чтобы не заблудиться.

@item I/32: The Grim Reaper
Всегда ли Вы считаете, что Ваша мышь перевернута???

@item I/43: Sokoban Revival
Помните? Это первый уровень оригинального Сокобана @dots{}  Он ведь не такой трудный!

@item I/65: Lasers 101
Поставьте два зеркала вверху и одно внизу. Перемещая зеркала и точно целясь,
Вы можете попасть лазерным лучом по всем Oxyd-камням.

@item I/72: Way to Go
Одна из синих точек ведет себя по-разному. Воспользуйтесь этим!

@item I/80: Meditation
Расположите шарики горизонтально.

@item II/15: Knock Knock!
Постучитесь в стены.

@item II/27: Twelve doors
Вы открыли все двери и все равно не можете пройти? Вы что-то пропустили!

@item II/40: Space Meditation
Слышали когда-нибудь о проблеме трех тел?

@item II/44: Pharaos' Tombs
Обратитесь к "Easy Shifting @enddots{}".

@item II/56: Easy Shifting @enddots{}
Обратитесь к ``Running Rings''.

@item II/57: Floppy Swapping
Первое---найдите дискету и волшебную палочку, они Вам понадобятся. Второе---всегда
носите дискету и волшебную палочку с собой. Третье---некоторые камни похожи, но
действуют не одинаково.

@item II/59: The Disappearing Block
Зажмите лазер.

@item II/65: Laser Magic
Время узнать несколько вещей о преобразовании объектов. Экспериментируйте!

@item II/69: Question of Speed
Или скорее: Вопрос начала???

@item II/77: Push Your Way
Сначала найдите волшебную палочку!

@item II/97: Tool Time
Прячьте опасные инструменты от детей.

@item II/99: Domain of Mysteries
Осторожно продвигайтесь к успеху.

@item II/100: Patterns
Есть ли здесь подобие?

@item III/14: Use the PIN
@enddots{} или воспользуйтесь Вашей любимой энциклопедией, если Вы не можете точно
вспомнить число.

@item III/16: Control Panel
Сообщение в левой комнате расскажет Вам, как расположить блоки в первой строке
переключателей. После этого, используйте коды цветов, показанных в левой комнате.

@item III/22: Portable Laser
Будьте признательны!

@item III/27: Tricks and Traps
Не можете выбраться из первого экрана? Сконцентрируйтесь сначала на мигающей точке.
Не можете найти последний Oxyd-камень? Активируйте три из больших мигающих точек
на первом экране и маленький на третьем экране.

@item III/28: Wells
Боитесь умереть?

@item III/29: Push? Pull!
Одна перестановка вверх -- Одна перестановка вниз -- Головоломка вправо -- Продолжите дальше!

@item III/40: Snow White
Три маленьких эскимоса -- Связанные в кольцо на ледяном поле -- Не могут найти их маленькие иглу -- Скрытые под снежным покровом.

@item III/43: The Ditch
Вы не можете решить этот уровень без потери своего "Я".

@item III/49: What's the Problem?
Ловушки по всей территории @dots{} это местность для медитации.

@item III/95: Jump and Run
Есть пружина, спрятанная за зеркалом.

@item IV/6: TNT Shortage?
С молотком проще!

@item IV/17: Flood Gates
Осторожное затопление определенных областей может пригодиться. Не покидайте первую
комнату без активации нижнего переключателя. Многие из всех нижних переключателей
действуют одинаково.

@item IV/25: Light Switches
Зажмите лазеры, если Вы не достаточно быстры.

@item IV/27: Robbery
Проберитесь в банк, через трещины в полу.

@item IV/34: Running Rings
Обратитесь к ``Pharao's Tomb''.

@item IV/39: How Many Spirals?
Некоторые люди выпрыгивают из окна при пожаре  -- поступите иначе.

@item IV/47: Just Moving Blocks?
Слишком много деревянных ящиков? Как бы Вам убрать один?

@item IV/48: Artillery
Пушечное ядро тоже открывает Oxyd-камни.

@item IV/54: Fire Safety
Переключатель вредит Вам? Уничтожьте его!

@item IV/64: The Flagstone Reaper
Это выполняется.

@item IV/65: Little Bit of Everything
Найдите способ уничтожения.

@item V/15: Solvable?
Не напоминает ли Вам о чем-то ЗСЮВ?

@item V/16: Draggers
Принято считать, что этот уровень---зло. Существует источник, спрятанный возле
Вашего начального положения.

@item V/24: Space Pirates
Этот уровень хитрый. Подожгите бомбу возле деревянных ящиков.

@item V/32: Walk the Plank
Не хватает пиратов, чтобы покорить этот уровень? Есть другой, более простой путь.

@item V/34: Island of Safety
Начните анализ с сотни.

@item V/45: Psycho Pushing
Толкай и беги.

@item V/58: Now What?
Когда Вы видите пересечение, что должно быть в следующем ряду?

@item V/78: Don't Be Greedy
Где-то в этом руководстве есть совет получше.

@item V/89: Ice-Bomb
Под камнем спрятан лучший совет.

@item V/91: Firefox
Пол горит быстрее.

@item VI/8: Orbitting
Не позволяйте ничему дотрагиваться до границ.

@item VI/23: Prepare Your Defense
Лазер изменяет не только предметы.

@item esprit 43
Принесите жертву вулкану.

@item esprit 52
Играйте до поры до времени.

@item esprit 100
Взорвите угол.

@item Oxyd Magnum 99 (level 22): Letter Bomb
Подорвите взрывающиеся камни.

@item PerOxyd 49 (level 22): Hidden Treasure
Удостоверьтесь, что у Вас всегда есть доступ к комнате с переключателем на полу. Потом ищите второй экран со "спрятанными сокровищами".

@end table

@node Благодарности,  , Спойлеры, Top
@chapter Благодарности

@menu
* Главные разработчики::
* Особые благодарности::
* Помощники::
* Используемое программное обеспечение::
@end menu


@node Главные разработчики, Особые благодарности, Благодарности, Благодарности
@section Главные разработчики

@table @strong
@item Thomas Bernhardt
Level design and testing

@item Raoul Bourquin
Руководство уровнями и дизайн, бесценные дополнения по всем вопросам

@item Siegfried Fennig
Дизайн уровней, графика

@item Martin Hawlisch
Дизайн уровней, графика, программирование

@item Daniel Heck
Главный разработчик, графика, документация

@item Ronald Lamprecht
XML, графический интерфейс, программирование основной части, документация

@item Andreas Lochmann
Coordination, Программирование, руководство уровнями, дизайн уровней, документация

@item Petr Machata
Дизайн уровней, программирование

@item Nobby
Level design and testing, score evaluation

@item Nat Pryce
Дизайн уровней

@item Jacob Scott
Дизайн уровней

@item Sven Siggelkow
Дизайн уровней и специальные знания Oxyd

@item Ralf Westram
Программирование, дизайн уровней
@end table


@node Особые благодарности, Помощники, Главные разработчики, Благодарности
@section Особые благодарности

@table @strong
@item Johannes Fortmann
Портирование на Mac OS X, немного программирования, графика

@item illmind
Forum mag-heut.net administration, Level design

@c Ожидается лицензия на добавление звуков
@c @item ``Cellar of Rats''
@c Звуковые эффекты

@item Jennifer Robertson
Graphics second generation

@item Jeremy Sawicki
Переработка формата файла Oxyd, Oxydlib

@item Meinolf Schneider
Оригинальная идея игры--@emph{Спасибо}!

@item Erich Schubert
Пакеты для Debian/Ubuntu

@item Andrew ``Necros'' Sega
Музыка в меню (@emph{Pentagonal Dreams})

@item David W. Skinner
Много уровней для Сокобана с сайта
@uref{http://users.bentonrea.com/~sasquatch/sokoban}

@item Clifford J. Tasner
Music second generation, Proof reading
@end table

@node Помощники, Используемое программное обеспечение, Особые благодарности, Благодарности
@section Помощники

Наша признательность различным меньшим помощникам:

@itemize @bullet
@item Another (Дизайн уровней)
@item Ash (Дизайн уровней)
@item Roberto Bardin (Дизайн уровней)
@item Helge Blohmer (Дизайн уровней)
@item Nathan Bronecke (Дизайн уровней)
@item Harry Bruder (LotM articles)
@item Alain Busser (Дизайн уровней, французский перевод игры и руководства)
@item Guy Busser (Дизайн уровней)
@item Richi B@"utzer (Дизайн уровней)
@item capkoh (Дизайн уровней)
@item Manfredi Carta (Дизайн уровней)
@item Christoph & Anita (Дизайн уровней)
@item daydreamer (Дизайн уровней)
@item Serge Dremuk (Русский перевод)
@item Joseph Dunne (Дизайн уровней)
@item Xerxes M. Dynatos (Дизайн уровней)
@item Edward (Дизайн уровней)
@item Manuel Eisentraut (Дизайн уровней)
@item Stephanie Fabian (Бесценные сообщения об ошибках)
@item Johann Freymuth (Дизайн уровней)
@item Roberto Garc@'ia (Испанский перевод)
@item Andy Geldmacher (Дизайн уровней)
@item Edwin Groothuis (Портирование на FreeBSD)
@item Daniel Hadas (Дизайн уровней)
@item Jonatan Hadas (Дизайн уровней)
@item Hairball (Дизайн уровней)
@item Immanuel Herrmann (Дизайн уровней)
@item Brian Huffman (Дизайн уровней)
@item Johannes H@"using (Дизайн уровней)
@item Icewing (Дизайн уровней)
@item M@'at@'e Lehel Juh@'asz (Венгерский перевод)
@item Samuele Kaplun (Итальянский перевод)
@item Manuel K@"onig (Дизайн уровней, сообщения об ошибках)
@item Jens-Christian Korth (Дизайн уровней)
@item Johannes Laire (Дизайн уровней)
@item Joona Laire (Дизайн уровней)
@item Markus Laire (Дизайн уровней)
@item Dominik Lehmann (Дизайн уровней)
@item Dominik Leipold (Дизайн уровней)
@item Ryan Lerch (AppData file)
@item Edward Leuf (Отзывы, сообщения об ошибках)
@item Ingo van Lil (Отзывы, сообщения об ошибках)
@item Frank van der Loo (Немецкий перевод)
@item Lurcane (Дизайн уровней)
@item Sidney Markowitz (Портирование на Mac OS X)
@item Barry & Lori Mead (Дизайн уровней)
@item Linda Mihalic (English proof reading)
@item moonpearl (Дизайн уровней)
@item Stephen Morley (Safalra) (Дизайн уровней)
@item Krishnamurti Lelis Lima Vieira Nunes (Португальский перевод)
@item Daniel Nylander (Шведский перевод)
@item Andreas Persenius (Дизайн уровней)
@item Mark Pulley (Дизайн уровней)
@item pzykosiz (Дизайн уровней)
@item Rudolf (Дизайн уровней)
@item Peter Santo (Дизайн уровней)
@item Tobias Schmidbauer (Windows installer and icon)
@item Lukas Sch@"uller (Дизайн уровней)
@item Achim Settelmeier (специальный файл RPM)
@item ShadowPhrogg32642342 (D@'aniel Borb@'ely) (Дизайн уровней)
@item Alex Smith (Дизайн уровней)
@item Alan Smithee (Дизайн уровней)
@item Jon Sneyers (Дизайн уровней)
@item Spaceman (Дизайн уровней)
@item Ulf Stegemann (Дизайн уровней)
@item J@"urgen Sticht (Дизайн уровней)
@item Mikke Surakka (Finnish translation)
@item Andrzej Szombierski (Дизайн уровней)
@item Tacvek (Обновление Lua 5.1)
@item James Taylor (Дизайн уровней)
@item Michael Terry (Файл .desktop)
@item Ray Wick (Дизайн уровней)
@item Joe Wreschnig (Руководство)
@item Zephyr (Дизайн уровней)
@item Yuriy Zhyromskiy (Русский перевод руководства)
@end itemize

@node Используемое программное обеспечение,  , Помощники, Благодарности
@section Используемое программное обеспечение

@table @strong

@item SDL
@uref{http://www.libsdl.org/}

@item SDL_image
@uref{http://www.libsdl.org/SDL_image}

@item SDL_mixer
@uref{http://www.libsdl.org/SDL_mixer}

@item Lua
@uref{http://www.lua.org}

@item Oxydlib
@uref{http://www.sawicki.us/oxyd}

@item toLua++
@uref{http://www.codenix.com/~tolua}

@item zipios
@uref{http://zipios.sourceforge.net}

@item Xerces C++
@uref{http://xml.apache.org/xerces-c}

@end table

@bye
