\input texinfo                              @c -*- texinfo -*-
@afourpaper
@documentlanguage de

@c @include{version.texi}
@set VERSION 1.0

@copying
Copyright @copyright{} 2003, 2004, 2005, 2006 Daniel Heck und Beitragende

Das Kopieren und Verteilen dieser Datei, mit oder ohne @"Anderungen, ist
gestattet, unter der Voraussetzung, dass obiger Copyright-Vermerk und
dieser Abschnitt erhalten bleiben.
@end copying

@setfilename enigma.info
@settitle Enigma Handbuch
@titlepage
@image{images/logo}
@center @titlefont{Enigma Handbuch}
@center f@"ur Version @value{VERSION}
@sp 2
@center Copyright @copyright{} 2003, 2004, 2005, 2006 Daniel Heck (@email{dheck@@gmx.de})
@c @title Enigma Handbuch
@c @subtitle for version 0.90
@c @author Daniel Heck (@email{dheck@@gmx.de})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top, Einleitung, (dir), (dir)
@top Enigma

Dieses Handuch beschreibt die Installation und das Spielprinzip von
Enigma.  Es bezieht sich auf Enigma Version @value{VERSION}.

Copyright @copyright{} 2003, 2004, 2005, 2006 Daniel Heck und Beitragende

Das Kopieren und Verteilen dieser Datei, mit oder ohne @"Anderungen, ist
gestattet, unter der Voraussetzung, dass obiger Copyright-Vermerk und
dieser Abschnitt erhalten bleiben.

@c @insertcopying
@end ifnottex

@menu
* Einleitung::                  Allgemeine Informationen @"uber Enigma
* Das Spiel::                   Spielprinzipien
* Einige Spielobjekte::         Beschreibung einiger Objekte im Spiel
* Fortgeschrittene Themen::     Weitere Features und Verwaltung
* Tipps und Tricks::            Tipps für einige schwierige Levels
* Autoren und Danksagungen::    Credits und `Thank You's
@end menu

@node Einleitung, Das Spiel, Top, Top
@chapter Einleitung

@menu
* Über Enigma::                 Einige Fakten über Enigma
* Installation::                Woher und wie installiert man Enigma
* Verbreiten von Enigma::       Gib Kopien an Deine Freunde!
@end menu


@node Über Enigma, Installation, Einleitung, Einleitung
@section @"Uber Enigma

Zu sagen, Enigma sei ein Rätselspiel, ist eine
Untertreibung. Tatsächlich ist Enigma eine riesige Sammlung von
Rätseln, jedes seiner 550 einzigartigen Level fordert die Intelligenz,
Geschicklichkeit und wahre Willensstärke seines Spielers aufs
Neue. Enigma ist einfach zu erlernen, herausfordernd zu spielen und
schwer zu schlagen. Es ist für fast alle Altersklassen geeignet. Es
enthält hunderte von Leveln. Und als ob das noch nicht genug wäre, ist
es zudem vollständig frei. Wenn Du Puzzlespiele magst und eine ruhige
Hand hast, wird Enigma Dich wahrscheinlich für Stunden nicht aus
seinem Bann lassen.

Das Ziel des Spieles ist es, Paare identisch gefärbter
@samp{Oxydsteine} zu finden und aufzudecken. Einfaches Prinzip?
Bestimmt. Einfach zu meistern? Sicherlich nicht! Versteckte Fallen,
riesige Labyrinthe, Laserstrahlen und nicht zuletzt zahllose haarige
Rätsel blockieren für gewöhnlich den direkten Weg zu den
Oxydsteinen. Enigmas Spielobjekte (von denen Hunderte existieren,
so dass keine Langeweile aufkommen kann) interagieren auf viele
unerwartete Weisen, and da viele von ihnen den Gesetzen der Physik
gehorchen (bzw. Enigmas spezieller Version der Physik), ist es nicht
immer einfach, sie mit der Maus zu kontrollieren...

Das ursprüngliche Ziel des Enigma-Projektes war es, den Geist der
Oxyd-Spiele-Serie am Leben zu erhalten, nachdem ihr Verleger 2002
entschied, das Spielegeschäft zu verlassen. Fans dieses berühmten
Spiels werden ihre D@'ej@`a-vus erleben. Aber über die Jahre hat
Enigma auch die Ideen zahlloser weiterer berühmter Spiele in sich
aufgenommen und ihnen seinen eigenen, ganz persönlichen Twist
hinzugefügt.

Enigma gibt es für Windows, Mac OS X und die meisten Linux- und
Unixversionen. Es wurde in viele Sprachen übersetzt, sogar dieses
Handbuch ist in mehreren Sprachen erhältlich.

Die offizielle @uref{http://www.nongnu.org/enigma, Homepage} von Enigma
versucht, die wichtigsten Informationen rund um Enigma zu sammeln: hier
findest Du Bildschirmfotos, die aktuellsten Versionen, Informationen
@"uber die Weiterentwicklung von Enigma und au@ss{}erdem die aktuellste
Ausgabe dieses @uref{http://www.nongnu.org/enigma/manual, Handbuchs}.
Die Entwickler von Enigma k@"onnen jederzeit unter der Email-Adresse
@email{enigma-devel@@nongnu.org} erreicht werden.

Enigma ist freie Software, d.h. Du bist ausdr@"ucklich dazu
aufgefordert, m@"oglichst viele Kopien an Deine Freunde zu verteilen
(@pxref{Verbreiten von Enigma}).  Enigma wird von einer kleinen Gruppe
von Freiwilligen entwickelt, und wir alle arbeiten in unserer Freizeit.
Wenn Dir das Spiel gef@"allt, w@"urden wir uns @"uber eine kleine
Email an die oben genannte Adresse sehr freuen, sozusagen als kleine
Anerkennung und Belohnung f@"ur die unz@"ahligen Stunden, die wir in
Enigma investiert haben.


@node Installation, Verbreiten von Enigma, Über Enigma, Einleitung
@section Installation

Die aktuellste Version von Enigma findet sich stets auf der offiziellen
@uref{http://www.nongnu.org/enigma/download.html, Download-Seite}. Diese
Seite stellt Pakete f@"ur die folgenden Betriebssysteme bereit:

@table @strong
@item Windows
Die Windows-Version von Enigma wird in Form eines einfachen
Installationsprogrammes vertrieben, das Enigma auf Ihrem Computer
einrichtet.  Laden Sie bitte einfach die bereitgestellte Datei auf Ihren
Computer und f@"uhren Sie sie aus, um die Installation zu starten.

@item Unix
Vorgefertigte Pakete existieren f@"ur einige verbreitete
Linux-Distributionen wie SUSE, Redhat und Debian.  F@"ur andere
Unix-@"ahnliche Betriebssysteme steht ist das Neukompilieren der
Quellcodes sicher die einfachste Lösung.

@item Mac OS X
Unter OS X ist keine Installation n@"otig; entpacken Sie einfach die
bereitgestellt @file{.dmg} or @file{.tar.gz} und kopieren Sie die
enthaltene Applikation an den von Ihnen gew@"unschten Ort.
@end table

Die Download-Seite enth@"alt @"ublicherweise detailliertere und aktuellere
Informationen (allerdings nur auf Englisch).  Falls Sie Probleme haben,
Enigma auf Ihrem Rechner zum Laufen zu bringen, z@"ogern Sie bitte nicht,
uns unter @email{enigma-devel@@nongnu.org} um Unterst@"utzung zu bitten.

@node Verbreiten von Enigma,  , Installation, Einleitung
@section Verbreitung von Enigma

Enigma ist freie Software und darf gem@"a@ss{} den Bedingungen der GNU General
Public License (GPL) verbreitet werden.  Die englische Fassung dieser
Lizenz ist jeder Kopie von Enigma beigelegt, die Datei hei@ss{}t
entweder @file{COPYING} oder @file{COPYING.txt}.  F@"ur den Fall, dass Sie
Enigma lediglich @emph{spielen} wollen, m@"ussen Sie die Lizenz eigentlich
nicht studieren (Sie h@"atten es ja vermutlich ohnehin nicht getan).  F@"ur
Sie besagt die Lizenz im Wesentlichen: Spielen Sie Enigma so viel Sie
wollen, so lange Sie wollen und geben Sie auf jeden Fall allen Ihren
Freunden eine Kopie!

Falls Sie dagegen @"Anderungen an Enigma vornehmen oder an der weiteren
Entwicklung teilnehmen m@"ochten, nehmen Sie sich bitte die Zeit, die
Lizenz durchzulesen.  Die GPL gew@"ahrleistet, dass Enigma auch in
Zukunft freie Software bleiben wird und ohne zus@"atzliche
Einschr@"ankungen benutzt und verbreitet werden kann.  Insbesondere
m@"ussen Derivate von Enigma unter sehr @"ahnlichen Lizenzbedingungen
wie Enigma selbst verf@"ugbar gemacht werden.

Die beiden vorstehenden Abs@"atze sind kein Ersatz f@"ur die eigentliche
Lizenz, lediglich eine Umschreibung ihrer Grundintention.  F@"ur Details
konsultieren Sie bitte den originalen Lizenztext oder fragen Sie auf der
Enigma-Mailingliste.

@node Das Spiel, Einige Spielobjekte, Einleitung, Top
@chapter Das Spiel

@menu
* Ganz zu Anfang::             Durch die Menüs navigieren und starten
* Spielregeln::                Wie man Enigma spielt
* Steuerung::                  Tastatur und Mauskommandos
@end menu


@node Ganz zu Anfang, Spielregeln, Das Spiel, Das Spiel
@section Ganz zu Anfang

Enigma pr@"asentiert sich nach dem Starten mit einem kleinen
Hauptmen@"u, von dem aus Sie ein neues Spiel starten, einige
Einstellungen @"andern oder das Spiel wieder verlassen k@"onnen, sobald
Sie genug haben.  Die folgenden Abschnitte werden Ihnen einen kurzen
@"Uberblick @"uber das Level-Men@"u und das Options-Men@"u geben,
in der Hoffnung, dass sich der Rest von selbst erschlie@ss{}t. Zu den
meisten Menüs kann man mit @key{F1} eine Hilfe aufrufen. 

@menu
* Das Level-Menü::               Wähle das nächste Level
* Das Levelpaket-Menü::          Bestimme ein Levelpaket
* Einstellungen::                Passe Enigma an
* Der Level-Inspektor::          Detailierte Informationen über ein Level
@end menu


@node Das Level-Menü, Das Levelpaket-Menü, Ganz zu Anfang, Ganz zu Anfang
@subsection Das Level-Menü

Wenn Sie im Hauptmen@"u den Eintrag ``Spiel starten'' anw@"ahlen,
landen Sie im Level-Men@"u, das ungef@"ahr folgenderma@ss{}en
aussieht:

@image{images/levelmenu,,7cm}

Der Bildschirm ist in drei Bereiche unterteilt: der obere Bereich
enth@"alt Informationen @"uber den gerade angew@"ahlten Level und
das aktuelle Levelpaket, der mittlere Bereich enth@"alt eine
@"Ubersicht @"uber alle verf@"ugbaren Landschaften, und am unteren
Bildschirmrand befindet sich eine Leiste mit Aktionskn@"opfen.

Durch die Landschafts-@"Ubersicht k@"onnen Sie mithilfe der kleinen
Pfeil-Kn@"opfe am rechten Rand oder mit den Pfeiltasten auf der Tastatur
navigieren.  Um ein neues Spiel zu starten, klicken Sie einfach auf das
gew@"unschte Vorschaubildchen oder Sie dr@"ucken die Eingabetaste, um
die momentan ausgew@"ahlte Landschaft zu starten.

Enigma has two difficulty settings: ``easy'' and ``normal.''  To
switch between easy and normal difficulty, press the center button in
the bottom row: switch to the icon displaying a silver medal with a
feather if you prefer simpler levels, or to the gold medal for the
normal, more difficult, game mode.

Not all levels are available in a simplified version; those that do
are marked with a feather (if you did not solve it yet) or with a
silver medal in the upper left corner of their preview image.

You can jump to the next level either by pressing @key{F5} or by pushing the
@key{>>|} button in the bottom row. The meaning of ``next'' in the
previous sentence depends on the
mode that you selected with the left-most icon button in the bottom row.

@itemize @bullet
@item 
A steady black marble icon stands for ``strictly next''. You will get the next level
in the level pack regardless of whether you already solved that level
or not.

@item
@c TODO: ``ready for awarding? also: use verb instead of -ing
The icon that displays medals that are ready for honoring stands for next 
unsolved mode. In this mode the @key{>>|} buttons moves to the next
unsolved level.

@item
The icon with the speeding black marble stands for the par mode. Par is the professional
average rating for a level.  This represents a score that should be reachable
for a skilled player. Levels where your score is equal to or lower
than this par value will be 
marked with the speeding marble icon. In this mode the
@key{>>|}  button moves to the next level with a score below par.

@item
Finally a world icon is provided for the world record hunt mode. If your score
is the best score ever recorded you will be honored with the world record icon.
If you select this mode a level will be played again and again until you
reach the world record. 

@c Of course, a world record is a rare event. But you may
@c use this mode just for training purposes and to lower your score a little bit.
@end itemize

Eine Landschaft ist m@"oglicherweise au@ss{}erdem mit einem kleinen
roten Dreieck mit Ausrufezeichen markiert: das Symbol signalisiert, dass
die Landschaft aktualisiert wurde, seit Sie sie zuletzt gel@"ost
haben. Sie sehen dies wahrscheinlich nur nach einem Update von Enigma.

Im Landschafts-Men@"u können folgende Tastaturk@"urzeln verwendet werden:

@table @kbd
@item @key{ESC}
R@"uckkehr zum Hauptmen@"u

@item @key{F1}
Hilfe

@item @key{F5}
Zur n@"achsten Landschaft, entspricht dem @key{>>|} button

@item Pfeiltasten
Auswahl einer Landschaft

@item @key{Eingabe}
Ausgw@"ahlte Landschaft spielen

@item @key{Leertaste}
N@"achstes Landschaftspaket

@item @key{Backspace}           @c TODO: 
Voriges Landschaftspaket

@end table

@node Das Levelpaket-Menü, Einstellungen, Das Level-Menü, Ganz zu Anfang
@subsection Das Levelpaket-Menü

Enigma comes with many levels.  Many, many levels, in fact.  To keeps
things orderly, they have been organized into ``level packs''.  And 
because every release of Enigma added more levels, we even 
had to organize the level packs themselves into ``groups''.  But
luckily, this is all a lot easier than it sounds.

To select the level pack, you have to enter the ``Level Pack'' menu to
which is accessible from the main menu or the level menu.

This menu shows the groups in the left column and the level packs of the 
selected group in the other columns to the right.  The official groups
that ship with Enigma are the following:

@itemize @bullet
@item @b{Enigma} - levels that are written just for Enigma 
@item @b{D@'ej@`a-vu} - levels that you may have seen before
@item @b{Sokoban}
@item @b{Facets} - special sortings and views of the levels above
@item @b{User} - personal levels and level packs like History, automatically generated by the 
system for the user.
@item @b{Development} - templates and unfinished levels from the Enigma Team
@item @b{All Packs}
@end itemize

Left clicks select a group or a level pack. 

For description of further features of level packs see @ref{User
Level Packs}.

@node Einstellungen, Der Level-Inspektor, Das Levelpaket-Menü, Ganz zu Anfang
@subsection Einstellungen

Das Optionsmen@"u erm@"oglichst es Ihnen, Enigma an Ihre Vorlieben anzupassen.

@c TODO: mit @"ubersetzung im Spiel abgleichen
@table @strong
@item Sprache (Language)
W@"ahlen Sie hier die Sprache, in der die Nachrichten in den Men@"us
und (falls verfügbar) in den Leveln dargestellt werden.

@item Vollbild
Schaltet zwischen Vollbild- und Fensterdarstellung um.  Sie k@"onnen dazu
auch das Tastenk@"urzel @kbd{Alt-@key{Eingabe}} verwenden, auch dann, wenn
Sie sich nicht im Optionsmen@"u befinden.  @emph{Hinweis:} Auf einigen
System wird diese Einstellung erst dann @"ubernommen, wenn Sie ins
Hauptmen@"u zur@"uckkehren.

@item Grafikmodus
Benutzen Sie diesen Knopf um die Bildschirmaufl@"osung zu w@"ahlen, die
Enigma f@"ur die Darstellung verwendet.  Diese Einstellung wird erst
@"ubernommen wenn Sie ins Hauptmen@"u zur@"uckkehren.

@item Gamma-Korrektur
Regeln Sie hier falls n@"otig die Helligkeit der Bildschirmdarstellung.

@item Maustempo
Stellen Sie hier ein, wie schnell Ihre Kugel beschleunigen soll wenn Sie
die Maus bewegen.  W@"ahrend des Spiels k@"onnen Sie dazu die linke/rechte
Pfeiltaste verwenden.

@item Effekt-Lautst@"arke
Regeln Sie hier die Lautst@"arke von Klangeffekten im Spiel.

@item Sound Schema
(F@"ur Oxyd-Kenner.) Mit diesem Knopf k@"onnen Sie das Klangschema
wechseln, das Enigma w@"ahrend des Spiels verwendet.  Nach Installation
der Oxyd-Daten k@"onnen Sie hier die originalen Soundeffekte einschalten.

@item Musik-Lautst@"arke
Regeln Sie hier die Lautst@"arke der Hintergrundmusik im Men@"u.

@c @item Music in game
@c Enigma can play music files during the game.  Turn this feature on or off.

@item Stereo
Erlaubt das Umschalten zwischen Links-Rechts-Stereo, Rechts-Links-Stereo
und Mono-Klang.

@item Update Bewertungen
Auf der Einstellung @samp{Auto} wird Enigma von Zeit zu Zeit
versuchen, aktuelle Bewertungen herunterzuladen. Dies betrifft
öffentliche Bewertungen, Weltrekorde, PAR-Zeiten etc.
@xref{Ergebnisse hochladen}.

@item Spielername
Gib hier den Namen oder Alias ein, der zusammen mit Deinen Ergebnissen
angezeigt werden soll, wenn Du enigma.score
hochlädst. @xref{Ergebnisse hochladen}.

@item Userpfad
Das Verzeichnis, in dem Enigma die Nutzerdaten speichert. Details
stehen im Referenzhandbuch.

@item Userbilderpfad
Das Verzeichnis, in dem Enigma Nutzerbilder speichert. Details stehen
im Referenzhandbuch.

@end table

@node Der Level-Inspektor, , Einstellungen, Ganz zu Anfang
@subsection Der Level-Inspektor

To view more detail information about a level you can call the level inspector.
Just right or control click on the level's preview image in the level menu.

You can compare your scores to the world record, the par, the level author's
score. Even some statistics about how many players solved a level are provided.

Besides all the other information that is described in detail in the reference
manual you can enter a small annotation to a level and can rate the level.

Please note the annotation text field may allow you just to enter ASCII 
characters depending on the system Enigma is running.

The rating is your personal impression of the level. @samp{-} stands for no
opinion. 0 - for very bad, 5 - for average, 10 - for best of best. The ratings
will be sent back with your scores (@pxref{Ergebnisse hochladen}).

Last but not least you can use the Level Inspector to view screen shots that 
you made while playing a level (@pxref{Steuerung}).


@node Spielregeln, Steuerung, Ganz zu Anfang, Das Spiel
@section Spielregeln

@menu
* Gewöhnliche Landschaften::
* Zwei-Spieler Landschaften::
* Meditations-Landschaften::
@end menu

Um Verwirrungen vorzubeugen: Die Begriffe ``Level'' und ``Landschaft''
werden synonym verwendet.

@node Gewöhnliche Landschaften, Zwei-Spieler Landschaften, Spielregeln, Spielregeln
@subsection Gew@"ohnliche Landschaften

Die grundlegende Idee hinter Enigma is recht einfach: in den meisten
Landschaften steuern Sie eine kleine schwarze Kugel, und Ihr Ziel ist
es, identische Paare sogenannter @emph{Oxyd-Steine} zu finden und zu
@"offnen.  Geschlossene Oxyd-Steine sehen folgenderma@ss{}en aus (es gibt
insgesamt vier @"au@ss{}erlich verschiedene Varianten, die sich aber alle
gleich verhalten):

@image{images/st-oxyds,,0.7cm}

Ber@"uhren Sie einen Oxyd-Stein mit Ihrer Kugel, dann @"offnet er sich
und zeigt ein blinkendes farbiges Symbol.  Je zwei Oxyd-Steine in jeder
Landschaft tragen dasselbe Symbol.  Diese Paare gilt es zu finden und
direkt hintereinander zu ber@"uhren, damit sie permantent ge@"offnet
bleiben---stimmen die Symbole nicht @"uberein, schlie@ss{}t sich der
erste Oxyd-Stein wieder.  Eine Landschaft gilt als gel@"ost, sobald Sie
alle Paare von Oxyd-Steinen gefunden und ge@"offnet haben.  In der
folgenden Abbildung sehen Sie ein Paar von gr@"unen Oxyd-Steinen, das
bereits ge@"offnet wurde.  Das Fragezeichen im blauen Oxyd-Stein
signalisiert, dass das zweite blaue Symbol noch irgendwo versteckt ist.

@image{images/intro-oxyd,,3cm}

@emph{@"Ubrigens: falls Sie es noch nicht getan haben, ist jetzt ein
guter Zeitpunkt, Enigma einmal zu starten und die ersten paar
Landschaften auszuprobieren!}

Sie k@"onnen auf dem Boden liegende Objekte aufsammeln, indem Sie
einfach dar@"uber rollen.  Das Inventar am unteren Rand des Bildschirms
zeigt alle Gegenst@"ande an, die sich gerade in Ihrem Besitz befinden.
Zu Beginn des Spiels sind Sie lediglich mit zwei Ersatzkugeln
ausger@"ustet.  Die folgende Abbildung zeigt ein Inventar, das bereits
eine Schaufel, ein St@"uck Papier, zwei Stangen Dynamit, Ihre
Ersatzleben und einen Regenschirm enth@"alt:

@image{images/intro-inventory,,1cm}

Das Objekt, das sich ganz links im Inventar befindet, kann durch
Dr@"ucken der linken Maustaste benutzt werden: damit legen Sie es
entweder auf dem Boden ab oder Sie aktivieren das Objekt.  Dynamit
beginnt beispielsweise zu brennen, wenn Sie es ablegen, und Sprungfedern
bewirken, dass Ihre Kugel in die Luft h@"upft.  Mit der rechten
Maustaste oder dem Mausrad k@"onnen Sie die Eintr@"age im Inventar
umordnen.

M@"ochten Sie einmal (aus welchem Grund auch immer) keine Objekte
einsammeln, halten Sie einfach eine der Maustasten gedr@"uckt, w@"ahrend
Sie die Kugel bewegen.  In einigen Situationen werden Sie das vielleicht
hilfreich finden.

Viele Steine lassen sich verschieben, wenn man sie nur kr@"aftig genug
anschubst.  Einer der n@"utzlichsten beweglichen Steine ist der
Holzstein, der etwa dazu verwendet werden kann, Br@"ucken @"uber Wasser
und Abgr@"unde zu errichten.  Das folgende Bild zeigt, wie man eine
Br@"ucke baut, indem man Holzsteine ins Wasser hineinschiebt:

@image{images/intro-plank,,4cm}

H@"aufig interagieren Spielobjekte auf @"uberraschende Weise:
Gegenst@"ande, die auf dem Boden liegen k@"onnen beispielsweise mit
Laserstrahlen oder beweglichen Steinen transformiert werden.  Und viele
Steine verhalten sich bei Berührung anders als normal wenn Sie bestimmte
Gegenst@"ande im ersten Eintrag Ihres Inventars haben (der Zauberstab
ist der ber@"uhmteste Vertreter dieser Gattung).

Eine letzte Bemerkung: F@"uhlen Sie sich nicht gleich entmutigt durch
die scheinbare Komplexit@"at des Spiels---die genaue Verhaltensweise der
meisten Objekte wird im Laufe der Zeit klar werden.  Einige der
merkw@"urdigeren Objekte werden au@ss{}erdem in @ref{Einige Spielobjekte}
n@"aher vorgestellt..

@node Zwei-Spieler Landschaften, Meditations-Landschaften, Gewöhnliche Landschaften, Spielregeln
@subsection Zwei-Spieler Landschaften

Zun@"achst eine schlechte Nachricht: Bislang unterst@"utzt Enigma noch keine
Spiele über lokale Netzwerke oder das Internet.  In dieser Hinsicht sind also
Zwei-Spieler Landschaften in Wirklichkeit Ein-Spieler Landschaften, in
denen Sie zwischen zwei Kugeln hin- und herschalten k@"onnen: die schwarze
Kugel kennen Sie bereits, und eine zus@"atzliche wei@ss{}e Kugel.

@image{images/intro-twoplayer,,7cm}

Zwei-Spieler Landschaften k@"onnen Sie an dem kleinen Yin-Yang Symbol in
Ihrem Inventar erkennen.  Wenn Sie dieses Objekt aktivieren, k@"onnen Sie
die Mauskontrolle auf die wei@ss{}e bzw. wieder zur@"uck auf die schwarze
Kugel legen.

@node Meditations-Landschaften,  , Zwei-Spieler Landschaften, Spielregeln
@subsection Meditations-Landschaften

Die sogenannten Meditationslandschaften unterscheiden sich im
Spielprinzip deutlich von gew@"ohnlichen Landschaften: hier besteht Ihre
Aufgabe nicht darin, passende Paare von Oxyd-Steinen zu finden, sondern
darin, eine Anzahl kleiner wei@ss{}er Kugeln in Vertiefungen im Boden zu
bef@"ordern.  Die Landschaft gilt als gel@"ost, sobald alle Kugeln in je
einer Mulde liegen und sich nicht mehr bewegen.

@image{images/intro-meditation,,3cm}

Aber seien Sie vorsichtig: Alle Kugeln bewegen sich gleichzeitig und
eine ruckartige Mausbewegung kann einige der Kugeln wieder aus Ihren
Vertiefungen herausschubsen.  Meditationslandschaften erfordern
gew@"ohnlich ein sehr ruhiges H@"andchen und eine ordentliche Portion
Geduld (sie hei@ss{} nicht umsonst Meditationslandschaften!).

@node Steuerung,  , Spielregeln, Das Spiel
@section Steuerung

Folgende Tabelle gibt einen @"Uberblick @"uber die Tastenbelegung im
Spiel.  Sie m@"ussen sich diese Liste nicht einpr@"agen---sie kann
w@"ahrend des Spiels jederzeit mit der @key{F1}-Taste abgerufen werden.

@table @kbd
@item Linke Maustaste
Benutze den ersten Gegenstand im Inventar

@item Rechte Maustaste / Mausrad
Sortiere die Gegenst@"ande im Inventar um

@item @key{ESC}
Zeige das Spielmen@"u

@item @key{F1}
Zeige den Hilfebildschirm

@item @key{F3}
Zerst@"ore die momentane Kugel

@item @key{Umschalt}+@key{F3}
Starte die Landschaft von Neuem

@item @key{F4}
Gehe zur n@"achsten Landschaft

@item @key{F5}
Gehe zur n@"achsten ungel@"osten Landschaft

@item @key{F10}
Erzeuge ein Bildschirmfoto

@item @key{Pfeil links}
Verringere Mausgeschwindigkeit

@item @key{Pfeil rechts}
Erh@"ohe Mausgeschwindigkeit

@item @key{Alt}-@key{RET}
Zwischen Vollbild- und Fensterdarstellung umschalten (funktioniert nicht
auf allen Systemen, notfalls kann das Einstellungsmen@"u verwendet
werden)

@item @key{Alt}-@key{X}
Kehre zur@"uck zum Landschaftsmen@"u
@end table

@node Einige Spielobjekte, Fortgeschrittene Themen, Das Spiel, Top
@chapter Einige Spielobjekte

There are dozens of different game objects you will see in Enigma's
levels. We just want to describe a small assorted set of them here. If
you're new to Enigma, you might want to start with the levels in the
tutorial pack? Just start Enigma, choose ``Level Pack'', then the
button ``Enigma'' in the upper-left corner, then ``Tutorial'' on the
right. Start with the first level ``Oxyd Stones 1''. The tutorial will
show you the most important objects and ideas, and some of the easier
levels of Enigma.

@menu
* Gegenstände::                 
* Steine::                      
@end menu

@node Gegenstände, Steine, Einige Spielobjekte, Einige Spielobjekte
@section Gegenst@"ande

@menu
* Sprengstoffe::
* Regenschirme::
* Fähnchen::
@end menu

@node Sprengstoffe, Regenschirme, Gegenstände, Gegenstände
@subsection Sprengstoffe

@image{images/it-explosives,,0.7cm}

In Enigma werden Sie im Laufe der Zeit @"uber drei verschiedene Arten
von Sprengstoff stolpern.  Am harmlosesten ist die Dynamitstange, mit
der Sie zwar nur geringen direkten Schaden anrichten k@"onnen, die sich
aber hervorragend als Z@"under f@"ur naheliegenede Bomben eignen.

Schwarze Bomben haben gen@"ugend Sprengladung, um tiefe L@"ocher in die
meisten Bodentypen zu rei@ss{}en und etwaige anliegende Gegenst@"ande zu
zerst@"oren.  F@"ur die meisten Zerst@"orungsarbeiten sind sie daher das
Mittel der Wahl.  Wei@ss{}e Bomben haben die kombinierte Sprengladung
von f@"unf schwarzen Bomben---bringen Sie ihre Kugel auf sichere Distanz
wenn Sie eine von ihnen brennen sehen!

@node Regenschirme, Fähnchen, Sprengstoffe, Gegenstände
@subsection Regenschirme

@image{images/it-umbrella,,0.7cm}

Benutzen Sie Schirme, um ihre Kugel f@"ur kurze Zeit (10 Sekunden um
genau zu sein) unverwundbar zu machen.  Solange wie ein Schirm aktiv
ist, wird ein wei@ss{}er blinkender Ring um Ihre Kugel herum angezeigt.
Sobald der Halo anf@"angt zu flackern ist Eile angesagt: Ihnen bleiben
dann nur noch 3 Sekunden, um Ihre Kugel in sicheres Terrain zu
manövrieren.

@node Fähnchen,  , Regenschirme, Gegenstände
@subsection F@"ahnchen

@image{images/it-flags,,0.7cm}

Fahnen sind insbesondere auf langen und gef@"ahrlichen Reisen hilfreiche
Begleiter.  Wenn Ihre Kugel unterwegs zu Bruch geht, k@"onnen Sie die
Landschaft dort fortsetzen, wo Sie zuletzt ein F@"ahnchen abgelegt
haben, und m@"ussen nicht noch einmal ganz am Anfang starten.  Es
existieren zwei verschiedene Fahnen: eine schwarze und eine wei@ss{}e,
die jeweils die Startposition der schwarzen oder wei@ss{}en Kugel
festlegen.

@node Steine,  , Gegenstände, Einige Spielobjekte
@section Steine  

@menu
* Tödliche Steine::             
* Wechselsteine::               
* Spiegel::                     
* Einbahn-Steine::                
* Shogunsteine::                
* Bolder-Steine::          
* Puzzle-Steine::               
* Poststeine::                  
@end menu

@node Tödliche Steine, Wechselsteine, Steine, Steine
@subsection Tödliche Steine

@image{images/st-lethal,,0.7cm}
Um zwei Steinarten sollten Sie auf jeden Fall einen m@"oglichst gro@ss{}en
Bogen schlagen, zumindest solange Sie keinen Schirm haben, um Ihre
kostbare Kugel zu sch@"utzen.

Der @emph{Totenkopfstein} ist genauso ungesund wie er aussieht; schon
die erste Ber@"uhrung ist t@"odlich.  Im Ernst, wir haben Sie gewarnt.
Vom Totenkopfstein gibt es auch noch eine besonders hinterh@"altige
unsichtbare Variante, also stecken Sie auf jeden Fall Ihre Zauberbrille
ein.

Der @emph{schwarze Ritter} bewacht oftmals wichtige Durchg@"ange, und
gew@"ohnlich hat er kein gesteigertes Interesse, sie passieren zu
lassen.  Bringen Sie ein gutes Argument mit, mit dem sie ihn
``@"uberzeugen'' k@"onnen.

@node Wechselsteine, Spiegel, Tödliche Steine, Steine
@subsection Wechselsteine

@image{images/st-swap,,0.7cm}

Wechselsteine bewegen sich nicht einfach auf das n@"achstgelegene Feld
wenn sie geschoben werden.  Stattdessen tauschen sie ihren Platz mit
demjenigen Stein, in den sie hineingeschoben werden.  Auf ein leeres
Feld kann so ein Stein gar nicht geschoben werden---die einzige
M@"oglichkeit, ihn von A nach B zu bef@"ordern ist also, ihn wiederholt
mit ``normalen'' Steinchen zu vertauschen.

@c @node Lasers, Mirrors, Swap Stones, Stones
@c @subsection Lasers

@c Both interesting and da

@node Spiegel, Einbahn-Steine, Wechselsteine, Steine
@subsection Spiegel

@image{images/st-mirrors,,0.7cm}

Laserstrahlen k@"onnen mithilfe der verschiedenen Spiegel umgelenkt oder
aufgespalten werden.  Es gibt in Enigma zwei grunds@"atzliche Typen von
Spiegeln: planare Spiegel und dreieckige Spiegel.  Ein planarer Spiegel
verh@"ahlt sich so, wie man es erwartet: Ein auftreffender Laserstrahl
wird reflektiert wenn er senkrecht zum Spiegel steht und er wird nach
links oder recht abgelenkt wenn er den Spiegel in einem Winkel von 45
Grad trifft.

Dreieckige Spiegel sind etwas kniffliger: Seine drei Seitenfl@"achen
verhalten sich wie gew@"ohnliche Spiegel, indem sie einen eintreffenden
Lichstrahl entweder zur@"uckwerfen oder umlenken.  F@"allt ein Strahl
allerdings auf die Spitze des Dreiecks, teilt er sich in @emph{zwei}
Strahlen auf, die den Spiegel in entgegengesetzter Richtung verlassen.

Beide Spiegeltypen gibt es au@ss{}erdem in halbtransparenter und
verschiebbarer Variante.  Halbtransparente Spiegel lenken einen
einkommenden Strahl zur H@"alfte um, lassen die andere H@"alfte
allerdings unver@"andert passieren.  Verschiebbare Spiegel sind auf
einem hellgrauen Stein befestigt, unbewegliche auf einem dunkelgrauen
Stein.

Die Ausrichtung eines Spiegels kann ge@"andert werden, indem man ihn
leicht mit einer Kugel ber@"uhrt.  Aber passen Sie auf bei Spiegeln, die
bereits im Strahlengang eines Lasers stehen: eine unbedachte @"Anderung
kann Sie schnell das Leben einer Kugel kosten!

@node Einbahn-Steine, Shogunsteine, Spiegel, Steine
@subsection Einbahn-Steine

@image{images/st-oneway,,0.7cm}

One can only pass these stones in one direction. Whole labyrinths can
be build out of them, but mostly they force you to complete one part
of the level before passing to the next one.

You have problems with a oneway stone that blocks your way? Maybe a
magic item is able to help you...

@node Shogunsteine, Bolder-Steine, Einbahn-Steine, Steine
@subsection Shogunsteine

@image{images/st-shogun,,0.7cm}

In einigen Landschaften werden Ihnen blinkende blaue Punkte auf dem
Boden begegnen.  Diese k@"onnen mit der richtigen Kombination von
@emph{Shogunsteinen} aktiviert werden, wobei sie dann @"ublicherweise
etwas Sinnvolles tun und z.B. eine T@"ur @"offnen oder einen Laser
ein- oder ausschalten.

Ein kleiner blinkender Punkt wird aktiviert, indem man einen Shogunstein
mit einem kleinen Loch auf den Punkt schiebt.  Um die gr@"o@ss{}eren
Punkte zu aktivieren ben@"otigen Sie mehrere Shogunsteine, die Sie
passend stapeln m@"ussen.  Um etwa einen mittelgr@"o@ss{}en Punkt zu
aktivieren m@"ussen Sie erst einen Shogunstein mit mittelgro@ss{}em Loch
auf den Punkt schieben und dann noch einen Shogunstein mit kleinem Loch
in den gr@"o@ss{}eren hineinschieben.  Bei gro@ss{}en blinkenden Punkten
verh@"ahlt es sich entsprechend.

@node Bolder-Steine, Puzzle-Steine, Shogunsteine, Steine
@subsection Bolder-Steine

@image{images/st-bolder,,0.7cm}

Bolder stones move in the direction
shown by the arrow on them until they bump into another stone.  Maybe
they block your way and you have to get rid of them some way or the
other. But never, never stand in front of one, as it shatters your
marble instantly, when the bolder stone overruns it!

However, you might make use of them, too, as they are able to open
oxyds, when they bump into them. And you can redirect the bolder
stones in several ways...

@node Puzzle-Steine, Poststeine, Bolder-Steine, Steine
@subsection Puzzle-Steine

Puzzlesteine verdanken ihren Namen der Tatsache, dass einzelne Steine
dieser Gattung zusammengesteckt werden k@"onnen wie die Teile eines
Puzzles.  Puzzlesteine haben an einigen oder allen ihrer vier Seiten
Anschl@"usse mit denen sie an benachbarte Puzzlesteine andocken
k@"onnen.  Sobald Puzzlesteine auf diese Weise zusammengef@"ugt sind,
bewegen sie sich zusammen als ein gro@ss{}er Puzzlestein.  Diese
gro@ss{}en Bl@"ocke k@"onnen Sie z.B. verwenden, um sichere Wege @"uber
Abgr@"unde oder Wasser zu konstruieren.

Puzzlesteine @"andern ihr Verhalten wenn man sie mit einem Zauberstab
ber@"uhrt.  Ist der ber@"uhrte Puzzlestein vollst@"andig verbunden, besitzt er
also keine offenen Anschl@"usse mehr, beginnt er augenblicklich zu
explodieren, Stein f@"ur Stein.  Existieren noch offene Anschl@"usse,
verschiebt die Ber@"uhrung mit dem Zauberstab alle Steine innerhalb einer
Zeile oder Spalte des Puzzlesteins um eine Stelle.  Am besten, Sie
probieren das einfach mal aus.

Berichten zufolge existiert noch eine seltene Abart des gew@"ohnlichen
Puzzlesteins.  Man findet ihre Vertreter haupts@"achlich in den
Landschaften von Oxyd 1 an, und man erkennt sie daran, dass sie
orangefarbene und nicht blaue Verbindungsrohre besitzen.  Diese
Puzzlesteine lassen sich nicht verschieben und man muss keinen
Zauberstab benutzen, um Zeilen und Spalten umzuordnen oder die Steine
zum explodieren zu bringen.

@node Poststeine,  , Puzzle-Steine, Steine
@subsection Poststeine

@image{images/st-mail,,0.7cm}

Poststeine dienen dazu, Gegenst@"ande aus Ihrem Inventar an einen
anderen Ort in der Landschaft zu transportieren.  Wenn Sie einen
Poststein ber@"uhren, wird der erste Gegenstand aus Ihrem Inventar
entfernt und an das Ende des Rohrsystems transportiert, das an den
Poststein angeschlossen ist.  In den meisten F@"allen m@"ussen Sie
dieses Rohrsystem erst einmal selbst zusammenbauen, etwa indem Sie die
einzelnen St@"ucke des Rohres nacheinander ``verschicken''.

Vorsicht: Poststeine funktionieren nicht mehr, sobald bereits ein
Gegenstand am Ende des Rohres liegt.  Wenn man nicht aufpasst, kann es
leicht passieren, dass man irrt@"umlich ein falsches Objekt verschickt,
das danach den Postweg versperrt!

@c @node Turnstiles, Bolder Stones, Puzzle Stones, Stones
@c @subsection Turnstiles



@c @node Bolder Stones, Elastics and Scissors, Turnstiles, Stones
@c @subsection Bolder Stones


@c @node Elastics and Scissors,  , Bolder Stones, Stones
@c @subsection Elastics and Scissors

@node Fortgeschrittene Themen, Tipps und Tricks, Einige Spielobjekte, Top
@chapter Fortgeschrittene Themen

@menu
* User Level Packs::            History, Search Results and Auto
* Backup::                      What to backup for security
* Ergebnisse hochladen::        Let the world know your success
* Updating Enigma::             Keeping scores and levels on an update
@end menu

@node User Level Packs, Backup, Fortgeschrittene Themen, Fortgeschrittene Themen
@section User Level Packs

@ref{Das Levelpaket-Menü} provides some additional features. The
@samp{User} group has three level packs that are initially empty:
@samp{Auto Folder}, @samp{History} and @samp{Search Result}.

By clicking on the @samp{Search} button in the level pack menu you can search in
the pool of levels. Just move the mouse to the text field and enter the string to
search. You may search within author, title and file name. The search is case 
insensitve. For example, you can search for the string ``jump''. The resulting levels will be 
provided as a level pack called ``Search Results''.

The level pack @samp{History} is updated automatically with every level you play.
This may be useful if you look for a level you played last week but do not know
the keywords to search for.

The @samp{Auto Folder} is a level pack that you can use to add new
levels, for example levels you download from the Internet or write yourself. The folder in which you should
store the levels is @samp{levels/auto} on the @samp{User Path} as shown in
@ref{Einstellungen}. Levels in this folder are automatically found and
loaded by Enigma when it starts.

Enigma provides many more useful features beyond the scope of this manual.
Please read the reference manual for more details.

@node Backup, Ergebnisse hochladen, User Level Packs, Fortgeschrittene Themen
@section Backup

If you are afraid of losing all your scores due to a hard drive
failure, or if you want to transfer your scores from one computer to
another, it is helpful to know how to back up Enigma's status
information.  To do that, first look up @samp{User Path} from Enigma's
@ref{Einstellungen} menu.  You can simply back up that folder---the
important files are @samp{enigma.score} and @samp{state.xml}.

@node Ergebnisse hochladen, Updating Enigma, Backup, Fortgeschrittene Themen
@section Ergebnisse hochladen

For registration of your scores you need to send us the @samp{enigma.score}
file located at the folder @samp{User Path}. Please look at the project
homepage for more detailed instructions.

To automatically download the updated world record score lists you just need to
enable the option @samp{Ratings Update}.

@node Updating Enigma, , Ergebnisse hochladen, Fortgeschrittene Themen
@section Updating Enigma

If you did not customize your old Enigma version simply deinstall the old
version and install the new one. That is all you have to do as your scores will
be updated automatically.

Just in case you added levels to the Enigma installation directories you have
to backup them prior deinstallation. After that you can safely deinstall the
old version and install the new one.

@c TODO: too technical (HOMEless, environment variable)@item
@c TODO: split in two sentences
The old score file @samp{~/.enigmarc2} for systems with a @samp{HOME} environment
variable or @samp{.../Application Data/enigmarc.lua2} for HOMEless Windows systems
is converted automatically to the new score format. You can remove the old score
after the first successful run of Enigma 1.00.

If you want to read levels that you saved from the old installation please
read the reference manual.

@node Tipps und Tricks, Autoren und Danksagungen, Fortgeschrittene Themen, Top
@chapter Tipps und Tricks

Dieses Kapitel enth@"alt Tipps f@"ur einige der etwas schwierigeren
Landschaften in Enigma.  Lesen Sie diese Hinweise bitte nur dann, wenn
Sie wirklich verzweifelt sind und nicht mehr weiter wissen.  Einige
Landschaften sind absichtlich schwer und selbst Enigma-Veteranen
ben@"otigen Stunden um sie zu knacken.  Einige Landschaften lassen sich
im einfachen Spielmodus (@pxref{Das Level-Menü}) leichter l@"osen.

@menu
* Tutorial::                    Komplettlösung für `Advanced Tutorial'
* Tipps::                       Hinweise für einige Landschaften
@end menu

@node Tutorial, Tipps, Tipps und Tricks, Tipps und Tricks
@section Tutorial

The landscapes in the ``Tutorial'' level pack are supposed to be easy.
Except for the last one, which is not...  This section of the manual was
contributed by Jacob Scott.

This walkthrough is for my level ``Advanced Tutorial'' in the
``Tutorial'' level pack (to change level packs, click on ``Level Pack''
at the bottom-left of the screen and select a level pack).  While you
are playing, you should read all the documents in a room as soon as
possible.

The final goal for this level, as for most Enigma levels, is to find and
hit ``Oxyd'' stones with your black ball.  When you hit an oxyd stone, it
opens and shows a color.  If you hit two oxyd stones of the same color in
a row, they will both stay open.  Once you've matched up all pairs of
oxyd stones in a level, you have completed the level.

The level contains about twenty rooms, organized into three separate
areas.  In the first area, you will be encounter some of the basic
blocks and floor types you will see in Enigma levels and solve a couple
of simple puzzles.  The second area is more challenging and will
introduce you to a useful technique in outthinking an active enemy.  The
third and final area leads you to experiment with more advanced
interactions between Enigma objects.  In this particular level, all of
the oxyd stones can be found in a single room at the end of area 3.

@subsection Gebiet 1

You start in a room surrounded by immovable walls except for a gap to
the right, some water near the bottom-left, and a closed gate near the
top-left.

Room 1: Go through the gap in the wall to the right.

Room 2: Simply avoid the blocks with pictures of skulls on them.

Room 3: Push the four wooden blocks into the water in the same row to
create a bridge to the opposite bank.  Now hit the blackish blocks to the
right.  Move the tan blocks out of the way (maybe to the left) and
bridge to the right with the two wooden blocks.

Room 4: Go close to the top.  When it begins to chase you, lead it to
the left and around the blocks in the center of the room.  Once the top
is far enough away from the entrance to the next room, run through.

Room 5: The only dangers here are the skulls near the bottom of the
room.  The first floor type is metal---this floor is similar to the
``leaves'' floor that you have been traveling on so far.  The next floor
type is ``red''---it is somewhat difficult to slow down or speed up on
this floor.  The third floor type is ice---there is little friction on
this floor.  The last floor type is space---there is no friction here;
you can't change velocity (speed and direction) when you are on this
type of floor.

Room 6: Simply go over the slopes.  Then exit to the left by passing over
the ``inverse'' floor---when you are on this type of floor and you push
the mouse (or similar controller) in one direction, the ball speeds up
in the opposite direction (if you are having trouble here, try turning
your mouse around 180 degrees).

Room 7: Try to get the extra ball by putting the movable block on the
lower trigger.  First hit it up one square and then left six
squares.  Next hit it five squares down and two squares to the right.
Finally hit it one square up and one square to the left. Take the extra
ball and then put the block on the other trigger to open the gate in the
left wall of the room.

Room 8: Take the dynamite (you will have to go on the ice) and drop it
in front of the yellow blocks to blow them up and get past.  The spade
is unnecessary but you should still experiment with it.

Room 9: Hit the lowest movable block to the left.  Now the boulders
trying to go to the right are blocking your path.  Hit the rightmost
movable block (to the left or to the right) to let the boulders
past.  Take the magic wand (don't accidentally hit any boulders when
the magic wand is in the front of your inventory) and hit the movable
block above the water down.  Now go back to the right of the room, put
the magic wand in the front of your inventory, and hit the top three
boulders of the long column (try not to get run over by any
boulders).  Hit the leftmost movable block to the left and go into the
next room.

Room 10: Hit the switch.  Now hit the two tan blocks up (one square
each).  Hit the middle (from top to bottom) wooden block to the left and
the wooden block that used to be right above it up into the water.  Hit
the rest of the blocks into the water in the same column (try not to
drown).  Now hit the window (the blue line) with high speed.  Take the
ball and cross over to the bridge into the first room.  From there go
through the open gate.

@subsection Gebiet 2

In area two, you will encounter a rotor, which is an active enemy of
your black ball.  Different rotors can act slightly differently, but they
are never very smart.  The way to get past it is to trick it to do what
you want it to do, while keeping yourself out of danger.

Look around this area (but don't hit the movable block yet).  You need to
get through the three closed gates at the top of this area.

First gate: Hit the white ball to the left (don't accidentally go
through the black one-way block) to free it (this may require a few
tries).  Take the spoon and hit the white ball through the white one-way
block hard enough so that it doesn't get stuck.  Now go through the black
one-way block and hit the white ball through the passageway.  Hit the
white ball hard enough through the next white one-way block so it
doesn't get stuck beneath it.  Once the white ball is through, use the
spoon; you restart at the beginning of the level and are no longer
trapped.  Go back up through the gate---the first gate near the top of
this room is open.

Second gate: Hit the movable block in the rightmost room of this area to
the right and run.  A document with useful information should appear in
the gate connecting area one and area two.  Bring the rotor (by making it
chase you, like you did with the top) to above the wall to the right of
the gate between the first two areas.  Run through the gate and go over
the bridge to the room below you.  Hit the switch to close the gate and
return to the room where you initially started.  You will no longer be
able to see the rotor---it won't be in the room where you will be---but
if you look carefully, you will be able to see where it is.  The goal
here is to, without exposing yourself to any danger, get the rotor to go
to a trigger and open a gate for you.  Get the rotor to follow you from
the top-right of this room to the top-left of the room.  It should be
pushed to the left by some slopes.  Bring the rotor down on the left
until it will not continue and you hear the sound of a trigger being
pushed.  Hit the switch to open the gate and return to area two---the
second gate should be open.

Third gate: Simply hit the movable block that the rotor started under
to the trigger in the room where it started.  Return to the room to your
left---the third gate should be open.  Go through the three open
gates.

@subsection Gebiet 3

In area three you need to explore the interactions between particular
Enigma objects.  Here you will find lasers, mirrors, and coins.  You will
need to solve a simple laser-and-mirror puzzle to get a laser to hit a
particular stone, which will open a bridge to the next room.  To get past
the next few rooms, you will need to create some new objects by hitting
existing objects with the laser beam.

In the first part of this area there are three mirrors and a laser with
a switch.

Room 1: You need to get the laser to hit the black stone.  Hit the
bottom-left mirror down one square and orient it so that it looks like a
``\'' by hitting it slowly (it should be thirty squares directly to the
left of the laser).  Hit the top-left mirror eight squares to the left,
one square down, and orient it so that it looks like a ``/'' (it should
be four squares directly above the previous mirror).  Hit the top-right
mirror two squares up and then three squares to the right (it should be
twenty-two squares directly to the right of the previous mirror and one
square below the black stone).  Put this mirror in the ``/''
orientation.  Now hit the switch to turn on the laser (don't get hit by
or roll over the laser beam).  Once it is completely up, go over the
bridge to your right.

Room 2: Take some coins and return to the previous room.  By turning off
and on the laser, hit one of the coins with the laser beam.  Take the
object produced (an umbrella), repeat the process, and take the second
umbrella.  Now drop one of the coins next to a mirror and hit the mirror
over it.  Hit this coin with a value of five with the laser beam to
produce a hammer.  Hit the hammer with the laser beam (by turning the
laser off and on) to produce a sword.  If you want some more balls, you
can hit mirrors over coins twice and hit the coins of increased value
(to ten, the highest possible) with the laser.  To return to the room
with the knights, put the mirrors back in their initial positions,
remove all objects blocking the laser, and hit the switch.  Now use the
right mouse button or the ``tab'' key to get the sword in the front
(left) of your inventory.  Hit some of the knights (four times each) to
get past.

Room 3: Use an umbrella and travel over the abyss to the room below you
and then into the room to your right.  If the ring surrounding you begins
to blink, use another umbrella.

Room 4: Simply match the oxyd stones by hitting oxyds of the same colors
as the activated oxyd stones (one at a time).  Don't hit the fart
stones (the black stones).  You win!


@node Tipps,  , Tutorial, Tipps und Tricks
@section Tipps

@table @strong

@item I/6: Welcome to the Machine
The message near the upper-right corner contains an important hint.

@item I/8: Easy?
Put the first shogun stone in the upper left corner, and the second
one @emph{above} the rightmost shogun dot.

@item I/31: Where Am I?
Make use of the wooden stones if you have lost your way. 

@item I/32: The Grim Reaper
Ever thought of turning your mouse upside-down???

@item I/43: Sokoban Revival
Remember? This was the first level in the original Sokoban...  So it
can't be that hard!

@item I/65: Lasers 101
Push two of the mirrors to the top and one to the bottom.  By moving the
mirrors around and by aiming carefully you can hit all of the Oxyd
stones with a laser beam.

@item I/72: Way to Go
One of the blue dots behaves differently.  Make use of that fact!

@item I/80: Meditation
Align the marbles horizontally. 

@item II/15: Knock Knock!
Knock the walls.

@item II/27: Twelve doors
You opened all the doors and still can't get through?  You must have
missed something!

@item II/40: Space Meditation
Ever heard of the three-body problem?

@item II/44: Pharaos' Tombs
Learn from ``Easy Shifting...''.

@item II/56: Easy Shifting...
Learn from ``Running Rings''.

@item II/57: Floppy Swapping
First, find the floppy disk and the magic wand, you will need them.
Second, always keep the floppy and the wand with you.  Third, some
stones look alike but don't behave alike.

@item II/59: The Disappearing Block
Jam the laser.

@item II/65: Laser Magic
It's time to learn a few things about object transformations.
Experiment!

@item II/69: Question of Speed
Or rather: Question of Seed???  

@item II/77: Push Your Way
Find the magic wand first! 

@item II/97: Tool Time
Hide dangerous tools from children.

@item II/99: Domain of Mysteries
Step careful in the ladder.

@item II/100: Patterns
Is there an echo?

@item III/14: Use the PIN
... or use your favourite encyclopedia if you don't recall the right
number.

@item III/16: Control Panel
The message in the left room tells you how to arrange the blocks on the
first rows of triggers.  From there, use the color codes indicated in
the left room. 

@item III/22: Portable Laser
Be grateful!

@item III/27: Tricks and Traps
Cannot get out of the first screen? Focus on the small blinking dot
first.  Cannot find the last Oxyd stone? Activate three of the large
blinking dots on the first screen and the small one on the third screen.

@item III/28: Wells
Afraid to die?

@item III/29: Push? Pull!
One swap up -- One swap down -- Puzzle to the right -- then keep on!

@item III/40: Snow White
Three little eskimoes -- Wand'ring on an ice field -- Couldn't find
their little igloos -- Deep under the snow shield.

@item III/43: The Ditch
You can't solve this level without a broken ego.

@item III/49: What's the Problem?
Decoys all over the place... this is a meditation landscape.

@item III/95: Jump and Run
There's a spring hidden under a mirror.

@item IV/6: TNT Shortage?
It's easier with a hammer!

@item IV/17: Flood Gates
Carefully flooding certain areas can be useful. Do not leave the first
room without activating the lower switch. The many switches on the
lower left all do the same.

@item IV/25: Light Switches
Jam the lasers in case you're not fast enough. 

@item IV/27: Robbery
Enter the bank through cracks in the floor. 

@item IV/34: Running Rings
Learn from ``Pharao's Tomb''.

@item IV/39: How Many Spirals?
Some people jump out of the window when there's fire -- do it the
other way around.

@item IV/47: Just Moving Blocks?
Too many wooden blocks? How could you remove one?

@item IV/48: Artillery
The cannonball also opens oxyds.

@item IV/54: Fire Safety
The trigger hurts you? Destroy it!

@item IV/64: The Flagstone Reaper
It processes.

@item IV/65: Little Bit of Everything
Find a way to shatter.

@item V/15: Solvable?
Does WNSE remind you of something?

@item V/16: Draggers
Admitted, this level is evil. There's a seed hidden near your starting
point.

@item V/24: Space Pirates
This one is tricky.  Ignite a bomb near the wooden stones.

@item V/32: Walk the Plank
Not enough of a pirate to master the this level?  There is a
different, easier route.

@item V/34: Island of Safety
First analyse one-hundreds.

@item V/45: Psycho Pushing
Hit and race.

@item V/58: Now What?
When you see the cross, what should the array show next?

@item V/78: Don't Be Greedy
There's a better hint somewhere in this manual.

@item V/89: Ice-Bomb
There's a better hint hidden under the oxyd.

@item V/91: Firefox
Floor burns faster.

@item VI/8: Orbitting
Don't let anything touch the borders.

@item VI/23: Prepare Your Defense
The laser changes more than items.

@item esprit 43
Sacrifice to the volcano.

@item esprit 52
Play it to the date.

@item esprit 100
Blast the corner.

@item Oxyd Magnum 99 (level 22): Letter Bomb
Bomb the bomb stones.

@item PerOxyd 49 (level 22): Hidden Treasure
Make sure you always have access to the room with the switch on the
floor.  Then search for the second screen with the ``hidden
treasure''.

@end table



@table @strong

@item #3: Pharaohs' Tombs
Nehmen Sie nicht das Papyrus.

@item #5: Sokoban Revival
Erinnern Sie sich?  Die erste Lagerhalle im originalen Sokoban sah
genauso aus...  So schwierig kann es also nicht sein!

@item #9: Floppy Swapping
Erstens, suchen Sie zun@"achst die beiden Disketten und den Zauberstab,
Sie werden sie ben@"otigen.  Zweitens, tragen Sie diese drei Objekte immer
bei sich.  Drittens, einige Steine sehen identisch aus, sind es aber
nicht.

@item #14: Lasers 101
Schieben Sie zwei der Spiegel an den oberen und einen an den unteren
Rand.  Wenn Sie die Spiel geeignet verschieben und sorgf@"altig zielen,
k@"onnen Sie alle Oxyd-Steine mit dem Laser erreichen.

@item #15: The Grim Reaper
Haben Sie schon einmal daran gedacht, Ihre Maus zumzudrehen???

@item #16: Knock Knock
H@"oren und sehen Sie genau hin.

@item #22: Way to Go
Einer der blauen Punkte verh@"alt sich anders als die anderen.  Nutzen Sie
das aus!

@item #29: Push Your Way
Suchen Sie zun@"achst den Zauberstab!

@item #30: Meditation
Richten Sie die Kugeln horizontal aus.

@item #32: Space Pirates
Diese Landschaft ist knifflig.  Z@"unden Sie eine Bombe in der N@"ahe der
Holzsteine.

@item #37: Twelve doors
Sie haben alle T@"uren ge@"offnet und kommen immer noch nicht durch? Sie
scheinen etwas @"ubersehen zu haben!

@item #48: Tricks and Traps
Sie kommen nicht aus dem ersten Raum? Richten Sie Ihre Aufmerksamkeit
zun@"achst auf den kleinen blinkenden Punkt.  Sie finden den letzten
Oxyd-Stein nicht? Aktivieren Sie drei gro@ss{}e blinkende Punkte im ersten
Bild und den kleinen im dritten.

@item #56: Hidden Treasure
Stellen Sie sicher, dass Sie immer in den Raum mit dem Bodenschalter
haben.  Suchen Sie dann nach dem zweiten Bildschirm mit dem
``versteckten Schatz''.

@item #71: Light Switches
Blockieren Sie die Laser wenn Sie nicht schnell genug sind.

@item #81: Flood Gates
Das vorsichtige @"Uberfluten von Gebieten kann hilfreich sein.  Legen Sie
auf jeden Fall den untern Schalter im ersten Raum um.

@item #96: Where Am I?
Nutzen Sie die Holzsteine falls Sie den @"Uberblick verlieren.

@item #110: Draggers
Zugegeben, die Landschaft ist b@"osartig.  Ein Steinsamen ist in der N@"ahe
der Startposition versteckt.

@item #113: Robbery
Dringen Sie durch br@"uchige Bodenplatten in die Bank ein.

@item #115: Laser Magic
Es ist an der Zeit, einige Grundlagen @"uber Objekt-Transformationen zu
lernen.  Experimentieren Sie!

@item #135: Control Panel
Die Nachricht im linken Raum erkl@"art, wie Sie die Steine auf der
ersten Schalterreihe platzieren m@"ussen.  Danach folgen Sie einfach den
im linken Raum angegebenen Farbcodes.

@end table

@table @strong
@item #12: Easy?
Schieben Sie den ersten Shogunstein in die obere linke Ecke und den
zweiten in das Feld @emph{@"uber} dem am weitesten rechts gelegenen
Punkt.

@item #16: Wells
Haben Sie Angst vor dem Tod?

@item #33: Welcome to the Machine
Die Nachricht in der oberen rechten Ecke enth@"alt einen wichtigen Tipp.

@item #34: Use the PIN
... oder greifen Sie zur Enzyklop@"adie Ihrer Wahl, falls Sie die Nummer
vergessen haben.

@item #62: TNT Shortage?
Mit einem Hammer geht's leichter!

@item #68: What's the Problem?
Falsche F@"ahrten @"uberall... es ist eine Meditationslandschaft.

@end table

@node Autoren und Danksagungen,  , Tipps und Tricks, Top
@chapter Autoren und Danksagungen

@menu
* Hauptentwickler::             
* Spezieller Dank::              
* Danksagungen::                
* Verwendete Software::           
@end menu


@node Hauptentwickler, Spezieller Dank, Autoren und Danksagungen, Autoren und Danksagungen
@section Hauptentwickler

@table @strong

@item Raoul Bourquin
Landschaftsverwaltung und -design, zahlreiche unschätzbare Erweiterungen

@item Siegfried Fennig
Landschaftsdesign, Grafik

@item Martin Hawlisch
Landschaftsdesign, Grafik, Programmierung

@item Daniel Heck
Hauptentwickler, Grafik, Dokumentation

@item Ronald Lamprecht
XML, Gui, Portierung, Kernel-Programmierung, Dokumentation

@item Andreas Lochmann
Programmierung, Landschaftsverwaltung und -design, Dokumentation

@item Petr Machata
Landschaftsdesign, Programmierung

@item Nat Pryce
Landschaftsdesign

@item Jacob Scott
Landschaftsdesign

@item Sven Siggelkow
Landschaftsdesign und besondere Oxyd-Expertise

@item Ralf Westram
Programmierung, Landschaftsdesign
@end table


@node Spezieller Dank, Danksagungen, Hauptentwickler, Autoren und Danksagungen
@section Spezieller Dank

@table @strong
@item Johannes Fortmann
Mac OS X Portierung, Programmierunterstützung, Grafik

@item Dustin Norlander
Designer der Schriftart ``Dustismo''

@item Jeremy Sawicki
Entschlüsselung des Oxyd-Dateiformats, Oxydlib

@item Erich Schubert
Debian/Ubuntu-Pakete

@item Meinolf Schneider
Ursprüngliche Spielidee--@emph{Vielen Dank}!

@item Andrew ``Necros'' Sega
Menü-Musik (@emph{Pentagonal Dreams})

@c waiting for licence to add the sounds
@c @item ``Cellar of Rats''
@c Sound effects

@item David W. Skinner
Viele Sokoban-Landschaften von
@uref{http://users.bentonrea.com/~sasquatch/sokoban}

@end table

@node Danksagungen, Verwendete Software, Spezieller Dank, Autoren und Danksagungen
@section Danksagungen

Für verschiedene kleinere Beiträge danken wir:

@itemize @bullet

@item
Roberto Bardin (Landschaftsdesign)

@item
Alain Busser (Landschaftsdesign, französische Übersetzung und Handbuch)

@item
Guy Busser (Landschaftsdesign)

@item
Richi B@"utzer (Landschaftsdesign)

@item
capkoh (Landschaftsdesign)

@item
Serge Dremuk (Russische Übersetzung)

@item
Xerxes M. Dynatos (Landschaftsdesign)

@item
Edward (Landschaftsdesign)

@item 
Stephanie Fabian (Wertvolle Fehlerberichte)

@item 
Edwin Groothuis (FreeBSD Portierung)

@item
Immanuel Herrmann (Landschaftsdesign)

@item
illmind (Landschaftsdesign)

@item
M@'at@'e Lehel Juh@'asz (Ungarische Übersetzung)

@item
Samuele Kaplun (Italienische Übersetzung)

@item
Jens-Christian Korth (Landschaftsdesign)

@item
Manuel K@"onig (Landschaftsdesign, Fehlerberichte)

@item
Dominik Lehmann (Landschaftsdesign)

@item
Edward Leuf (Feedback, Fehlerberichte)

@item
Ingo van Lil (Feedback, Fehlerberichte)

@item
Frank van der Loo (Niederländische Übersetzung)

@item
Sidney Markowitz (Mac OS X Portierung)

@item
Samuel El?as Mart@'inez ?lvarez (Spanische Übersetzung)

@item
moonpearl (Landschaftsdesign)

@item
Daniel Nylander (Schwedische Übersetzung)

@item
Peter Santo (Landschaftsdesign)

@item
Lukas Sch@"uller (Landschaftsdesign)

@item 
Achim Settelmeier (RPM specfile)

@item 
Jon Sneyers (Landschaftsdesign)

@item
Spaceman (Landschaftsdesign)

@item
J@"urgen Sticht (Landschaftsdesign)

@item 
Andrzej Szombierski (Landschaftsdesign)

@item
Tacvek (Lua 5.1 Upgrade)

@item
Michael Terry (.desktop file)

@item
Ray Wick (Landschaftsdesign)

@item
Joe Wreschnig (Manual page für Unix)

@end itemize

@node Verwendete Software,  , Danksagungen, Autoren und Danksagungen
@section Verwendete Software

@table @strong

@item SDL 
@uref{http://www.libsdl.org/}

@item SDL_image
@uref{http://www.libsdl.org/SDL_image}

@item SDL_mixer
@uref{http://www.libsdl.org/SDL_mixer}

@item Lua
@uref{http://www.lua.org}

@item Oxydlib
@uref{http://www.sawicki.us/oxyd}

@item tolua
@uref{http://www.tecgraf.puc-rio.br/~celes/tolua}

@item zipios
@uref{http://zipios.sourceforge.net}

@end table

@bye
